// Code generated by ent, DO NOT EDIT.

package modelpricingoverride

import (
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/internal/domain"
)

const (
	// Label holds the string label denoting the modelpricingoverride type in the database.
	Label = "model_pricing_override"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAdapter holds the string denoting the adapter field in the database.
	FieldAdapter = "adapter"
	// FieldModelPattern holds the string denoting the model_pattern field in the database.
	FieldModelPattern = "model_pattern"
	// FieldBillingMode holds the string denoting the billing_mode field in the database.
	FieldBillingMode = "billing_mode"
	// FieldInputPrice holds the string denoting the input_price field in the database.
	FieldInputPrice = "input_price"
	// FieldOutputPrice holds the string denoting the output_price field in the database.
	FieldOutputPrice = "output_price"
	// FieldCacheWritePrice holds the string denoting the cache_write_price field in the database.
	FieldCacheWritePrice = "cache_write_price"
	// FieldCacheReadPrice holds the string denoting the cache_read_price field in the database.
	FieldCacheReadPrice = "cache_read_price"
	// FieldImageInputPrice holds the string denoting the image_input_price field in the database.
	FieldImageInputPrice = "image_input_price"
	// FieldImageOutputPrice holds the string denoting the image_output_price field in the database.
	FieldImageOutputPrice = "image_output_price"
	// FieldPerRequestPrice holds the string denoting the per_request_price field in the database.
	FieldPerRequestPrice = "per_request_price"
	// FieldIntervals holds the string denoting the intervals field in the database.
	FieldIntervals = "intervals"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// Table holds the table name of the modelpricingoverride in the database.
	Table = "model_pricing_overrides"
)

// Columns holds all SQL columns for modelpricingoverride fields.
var Columns = []string{
	FieldID,
	FieldAdapter,
	FieldModelPattern,
	FieldBillingMode,
	FieldInputPrice,
	FieldOutputPrice,
	FieldCacheWritePrice,
	FieldCacheReadPrice,
	FieldImageInputPrice,
	FieldImageOutputPrice,
	FieldPerRequestPrice,
	FieldIntervals,
	FieldStatus,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// AdapterValidator is a validator for the "adapter" field. It is called by the builders before save.
	AdapterValidator func(string) error
	// ModelPatternValidator is a validator for the "model_pattern" field. It is called by the builders before save.
	ModelPatternValidator func(string) error
	// DefaultBillingMode holds the default value on creation for the "billing_mode" field.
	DefaultBillingMode string
	// BillingModeValidator is a validator for the "billing_mode" field. It is called by the builders before save.
	BillingModeValidator func(string) error
	// DefaultIntervals holds the default value on creation for the "intervals" field.
	DefaultIntervals []domain.ModelPricingInterval
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
)

// OrderOption defines the ordering options for the ModelPricingOverride queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAdapter orders the results by the adapter field.
func ByAdapter(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAdapter, opts...).ToFunc()
}

// ByModelPattern orders the results by the model_pattern field.
func ByModelPattern(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelPattern, opts...).ToFunc()
}

// ByBillingMode orders the results by the billing_mode field.
func ByBillingMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBillingMode, opts...).ToFunc()
}

// ByInputPrice orders the results by the input_price field.
func ByInputPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInputPrice, opts...).ToFunc()
}

// ByOutputPrice orders the results by the output_price field.
func ByOutputPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutputPrice, opts...).ToFunc()
}

// ByCacheWritePrice orders the results by the cache_write_price field.
func ByCacheWritePrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCacheWritePrice, opts...).ToFunc()
}

// ByCacheReadPrice orders the results by the cache_read_price field.
func ByCacheReadPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCacheReadPrice, opts...).ToFunc()
}

// ByImageInputPrice orders the results by the image_input_price field.
func ByImageInputPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImageInputPrice, opts...).ToFunc()
}

// ByImageOutputPrice orders the results by the image_output_price field.
func ByImageOutputPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImageOutputPrice, opts...).ToFunc()
}

// ByPerRequestPrice orders the results by the per_request_price field.
func ByPerRequestPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPerRequestPrice, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}
