// Code generated by ent, DO NOT EDIT.

package modelpricingoverride

import (
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldLTE(FieldID, id))
}

// Adapter applies equality check predicate on the "adapter" field. It's identical to AdapterEQ.
func Adapter(v string) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldEQ(FieldAdapter, v))
}

// ModelPattern applies equality check predicate on the "model_pattern" field. It's identical to ModelPatternEQ.
func ModelPattern(v string) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldEQ(FieldModelPattern, v))
}

// BillingMode applies equality check predicate on the "billing_mode" field. It's identical to BillingModeEQ.
func BillingMode(v string) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldEQ(FieldBillingMode, v))
}

// InputPrice applies equality check predicate on the "input_price" field. It's identical to InputPriceEQ.
func InputPrice(v float64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldEQ(FieldInputPrice, v))
}

// OutputPrice applies equality check predicate on the "output_price" field. It's identical to OutputPriceEQ.
func OutputPrice(v float64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldEQ(FieldOutputPrice, v))
}

// CacheWritePrice applies equality check predicate on the "cache_write_price" field. It's identical to CacheWritePriceEQ.
func CacheWritePrice(v float64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldEQ(FieldCacheWritePrice, v))
}

// CacheReadPrice applies equality check predicate on the "cache_read_price" field. It's identical to CacheReadPriceEQ.
func CacheReadPrice(v float64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldEQ(FieldCacheReadPrice, v))
}

// ImageInputPrice applies equality check predicate on the "image_input_price" field. It's identical to ImageInputPriceEQ.
func ImageInputPrice(v float64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldEQ(FieldImageInputPrice, v))
}

// ImageOutputPrice applies equality check predicate on the "image_output_price" field. It's identical to ImageOutputPriceEQ.
func ImageOutputPrice(v float64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldEQ(FieldImageOutputPrice, v))
}

// PerRequestPrice applies equality check predicate on the "per_request_price" field. It's identical to PerRequestPriceEQ.
func PerRequestPrice(v float64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldEQ(FieldPerRequestPrice, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldEQ(FieldStatus, v))
}

// AdapterEQ applies the EQ predicate on the "adapter" field.
func AdapterEQ(v string) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldEQ(FieldAdapter, v))
}

// AdapterNEQ applies the NEQ predicate on the "adapter" field.
func AdapterNEQ(v string) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldNEQ(FieldAdapter, v))
}

// AdapterIn applies the In predicate on the "adapter" field.
func AdapterIn(vs ...string) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldIn(FieldAdapter, vs...))
}

// AdapterNotIn applies the NotIn predicate on the "adapter" field.
func AdapterNotIn(vs ...string) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldNotIn(FieldAdapter, vs...))
}

// AdapterGT applies the GT predicate on the "adapter" field.
func AdapterGT(v string) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldGT(FieldAdapter, v))
}

// AdapterGTE applies the GTE predicate on the "adapter" field.
func AdapterGTE(v string) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldGTE(FieldAdapter, v))
}

// AdapterLT applies the LT predicate on the "adapter" field.
func AdapterLT(v string) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldLT(FieldAdapter, v))
}

// AdapterLTE applies the LTE predicate on the "adapter" field.
func AdapterLTE(v string) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldLTE(FieldAdapter, v))
}

// AdapterContains applies the Contains predicate on the "adapter" field.
func AdapterContains(v string) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldContains(FieldAdapter, v))
}

// AdapterHasPrefix applies the HasPrefix predicate on the "adapter" field.
func AdapterHasPrefix(v string) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldHasPrefix(FieldAdapter, v))
}

// AdapterHasSuffix applies the HasSuffix predicate on the "adapter" field.
func AdapterHasSuffix(v string) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldHasSuffix(FieldAdapter, v))
}

// AdapterEqualFold applies the EqualFold predicate on the "adapter" field.
func AdapterEqualFold(v string) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldEqualFold(FieldAdapter, v))
}

// AdapterContainsFold applies the ContainsFold predicate on the "adapter" field.
func AdapterContainsFold(v string) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldContainsFold(FieldAdapter, v))
}

// ModelPatternEQ applies the EQ predicate on the "model_pattern" field.
func ModelPatternEQ(v string) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldEQ(FieldModelPattern, v))
}

// ModelPatternNEQ applies the NEQ predicate on the "model_pattern" field.
func ModelPatternNEQ(v string) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldNEQ(FieldModelPattern, v))
}

// ModelPatternIn applies the In predicate on the "model_pattern" field.
func ModelPatternIn(vs ...string) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldIn(FieldModelPattern, vs...))
}

// ModelPatternNotIn applies the NotIn predicate on the "model_pattern" field.
func ModelPatternNotIn(vs ...string) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldNotIn(FieldModelPattern, vs...))
}

// ModelPatternGT applies the GT predicate on the "model_pattern" field.
func ModelPatternGT(v string) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldGT(FieldModelPattern, v))
}

// ModelPatternGTE applies the GTE predicate on the "model_pattern" field.
func ModelPatternGTE(v string) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldGTE(FieldModelPattern, v))
}

// ModelPatternLT applies the LT predicate on the "model_pattern" field.
func ModelPatternLT(v string) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldLT(FieldModelPattern, v))
}

// ModelPatternLTE applies the LTE predicate on the "model_pattern" field.
func ModelPatternLTE(v string) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldLTE(FieldModelPattern, v))
}

// ModelPatternContains applies the Contains predicate on the "model_pattern" field.
func ModelPatternContains(v string) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldContains(FieldModelPattern, v))
}

// ModelPatternHasPrefix applies the HasPrefix predicate on the "model_pattern" field.
func ModelPatternHasPrefix(v string) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldHasPrefix(FieldModelPattern, v))
}

// ModelPatternHasSuffix applies the HasSuffix predicate on the "model_pattern" field.
func ModelPatternHasSuffix(v string) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldHasSuffix(FieldModelPattern, v))
}

// ModelPatternEqualFold applies the EqualFold predicate on the "model_pattern" field.
func ModelPatternEqualFold(v string) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldEqualFold(FieldModelPattern, v))
}

// ModelPatternContainsFold applies the ContainsFold predicate on the "model_pattern" field.
func ModelPatternContainsFold(v string) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldContainsFold(FieldModelPattern, v))
}

// BillingModeEQ applies the EQ predicate on the "billing_mode" field.
func BillingModeEQ(v string) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldEQ(FieldBillingMode, v))
}

// BillingModeNEQ applies the NEQ predicate on the "billing_mode" field.
func BillingModeNEQ(v string) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldNEQ(FieldBillingMode, v))
}

// BillingModeIn applies the In predicate on the "billing_mode" field.
func BillingModeIn(vs ...string) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldIn(FieldBillingMode, vs...))
}

// BillingModeNotIn applies the NotIn predicate on the "billing_mode" field.
func BillingModeNotIn(vs ...string) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldNotIn(FieldBillingMode, vs...))
}

// BillingModeGT applies the GT predicate on the "billing_mode" field.
func BillingModeGT(v string) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldGT(FieldBillingMode, v))
}

// BillingModeGTE applies the GTE predicate on the "billing_mode" field.
func BillingModeGTE(v string) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldGTE(FieldBillingMode, v))
}

// BillingModeLT applies the LT predicate on the "billing_mode" field.
func BillingModeLT(v string) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldLT(FieldBillingMode, v))
}

// BillingModeLTE applies the LTE predicate on the "billing_mode" field.
func BillingModeLTE(v string) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldLTE(FieldBillingMode, v))
}

// BillingModeContains applies the Contains predicate on the "billing_mode" field.
func BillingModeContains(v string) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldContains(FieldBillingMode, v))
}

// BillingModeHasPrefix applies the HasPrefix predicate on the "billing_mode" field.
func BillingModeHasPrefix(v string) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldHasPrefix(FieldBillingMode, v))
}

// BillingModeHasSuffix applies the HasSuffix predicate on the "billing_mode" field.
func BillingModeHasSuffix(v string) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldHasSuffix(FieldBillingMode, v))
}

// BillingModeEqualFold applies the EqualFold predicate on the "billing_mode" field.
func BillingModeEqualFold(v string) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldEqualFold(FieldBillingMode, v))
}

// BillingModeContainsFold applies the ContainsFold predicate on the "billing_mode" field.
func BillingModeContainsFold(v string) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldContainsFold(FieldBillingMode, v))
}

// InputPriceEQ applies the EQ predicate on the "input_price" field.
func InputPriceEQ(v float64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldEQ(FieldInputPrice, v))
}

// InputPriceNEQ applies the NEQ predicate on the "input_price" field.
func InputPriceNEQ(v float64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldNEQ(FieldInputPrice, v))
}

// InputPriceIn applies the In predicate on the "input_price" field.
func InputPriceIn(vs ...float64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldIn(FieldInputPrice, vs...))
}

// InputPriceNotIn applies the NotIn predicate on the "input_price" field.
func InputPriceNotIn(vs ...float64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldNotIn(FieldInputPrice, vs...))
}

// InputPriceGT applies the GT predicate on the "input_price" field.
func InputPriceGT(v float64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldGT(FieldInputPrice, v))
}

// InputPriceGTE applies the GTE predicate on the "input_price" field.
func InputPriceGTE(v float64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldGTE(FieldInputPrice, v))
}

// InputPriceLT applies the LT predicate on the "input_price" field.
func InputPriceLT(v float64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldLT(FieldInputPrice, v))
}

// InputPriceLTE applies the LTE predicate on the "input_price" field.
func InputPriceLTE(v float64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldLTE(FieldInputPrice, v))
}

// InputPriceIsNil applies the IsNil predicate on the "input_price" field.
func InputPriceIsNil() predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldIsNull(FieldInputPrice))
}

// InputPriceNotNil applies the NotNil predicate on the "input_price" field.
func InputPriceNotNil() predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldNotNull(FieldInputPrice))
}

// OutputPriceEQ applies the EQ predicate on the "output_price" field.
func OutputPriceEQ(v float64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldEQ(FieldOutputPrice, v))
}

// OutputPriceNEQ applies the NEQ predicate on the "output_price" field.
func OutputPriceNEQ(v float64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldNEQ(FieldOutputPrice, v))
}

// OutputPriceIn applies the In predicate on the "output_price" field.
func OutputPriceIn(vs ...float64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldIn(FieldOutputPrice, vs...))
}

// OutputPriceNotIn applies the NotIn predicate on the "output_price" field.
func OutputPriceNotIn(vs ...float64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldNotIn(FieldOutputPrice, vs...))
}

// OutputPriceGT applies the GT predicate on the "output_price" field.
func OutputPriceGT(v float64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldGT(FieldOutputPrice, v))
}

// OutputPriceGTE applies the GTE predicate on the "output_price" field.
func OutputPriceGTE(v float64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldGTE(FieldOutputPrice, v))
}

// OutputPriceLT applies the LT predicate on the "output_price" field.
func OutputPriceLT(v float64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldLT(FieldOutputPrice, v))
}

// OutputPriceLTE applies the LTE predicate on the "output_price" field.
func OutputPriceLTE(v float64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldLTE(FieldOutputPrice, v))
}

// OutputPriceIsNil applies the IsNil predicate on the "output_price" field.
func OutputPriceIsNil() predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldIsNull(FieldOutputPrice))
}

// OutputPriceNotNil applies the NotNil predicate on the "output_price" field.
func OutputPriceNotNil() predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldNotNull(FieldOutputPrice))
}

// CacheWritePriceEQ applies the EQ predicate on the "cache_write_price" field.
func CacheWritePriceEQ(v float64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldEQ(FieldCacheWritePrice, v))
}

// CacheWritePriceNEQ applies the NEQ predicate on the "cache_write_price" field.
func CacheWritePriceNEQ(v float64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldNEQ(FieldCacheWritePrice, v))
}

// CacheWritePriceIn applies the In predicate on the "cache_write_price" field.
func CacheWritePriceIn(vs ...float64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldIn(FieldCacheWritePrice, vs...))
}

// CacheWritePriceNotIn applies the NotIn predicate on the "cache_write_price" field.
func CacheWritePriceNotIn(vs ...float64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldNotIn(FieldCacheWritePrice, vs...))
}

// CacheWritePriceGT applies the GT predicate on the "cache_write_price" field.
func CacheWritePriceGT(v float64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldGT(FieldCacheWritePrice, v))
}

// CacheWritePriceGTE applies the GTE predicate on the "cache_write_price" field.
func CacheWritePriceGTE(v float64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldGTE(FieldCacheWritePrice, v))
}

// CacheWritePriceLT applies the LT predicate on the "cache_write_price" field.
func CacheWritePriceLT(v float64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldLT(FieldCacheWritePrice, v))
}

// CacheWritePriceLTE applies the LTE predicate on the "cache_write_price" field.
func CacheWritePriceLTE(v float64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldLTE(FieldCacheWritePrice, v))
}

// CacheWritePriceIsNil applies the IsNil predicate on the "cache_write_price" field.
func CacheWritePriceIsNil() predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldIsNull(FieldCacheWritePrice))
}

// CacheWritePriceNotNil applies the NotNil predicate on the "cache_write_price" field.
func CacheWritePriceNotNil() predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldNotNull(FieldCacheWritePrice))
}

// CacheReadPriceEQ applies the EQ predicate on the "cache_read_price" field.
func CacheReadPriceEQ(v float64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldEQ(FieldCacheReadPrice, v))
}

// CacheReadPriceNEQ applies the NEQ predicate on the "cache_read_price" field.
func CacheReadPriceNEQ(v float64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldNEQ(FieldCacheReadPrice, v))
}

// CacheReadPriceIn applies the In predicate on the "cache_read_price" field.
func CacheReadPriceIn(vs ...float64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldIn(FieldCacheReadPrice, vs...))
}

// CacheReadPriceNotIn applies the NotIn predicate on the "cache_read_price" field.
func CacheReadPriceNotIn(vs ...float64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldNotIn(FieldCacheReadPrice, vs...))
}

// CacheReadPriceGT applies the GT predicate on the "cache_read_price" field.
func CacheReadPriceGT(v float64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldGT(FieldCacheReadPrice, v))
}

// CacheReadPriceGTE applies the GTE predicate on the "cache_read_price" field.
func CacheReadPriceGTE(v float64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldGTE(FieldCacheReadPrice, v))
}

// CacheReadPriceLT applies the LT predicate on the "cache_read_price" field.
func CacheReadPriceLT(v float64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldLT(FieldCacheReadPrice, v))
}

// CacheReadPriceLTE applies the LTE predicate on the "cache_read_price" field.
func CacheReadPriceLTE(v float64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldLTE(FieldCacheReadPrice, v))
}

// CacheReadPriceIsNil applies the IsNil predicate on the "cache_read_price" field.
func CacheReadPriceIsNil() predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldIsNull(FieldCacheReadPrice))
}

// CacheReadPriceNotNil applies the NotNil predicate on the "cache_read_price" field.
func CacheReadPriceNotNil() predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldNotNull(FieldCacheReadPrice))
}

// ImageInputPriceEQ applies the EQ predicate on the "image_input_price" field.
func ImageInputPriceEQ(v float64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldEQ(FieldImageInputPrice, v))
}

// ImageInputPriceNEQ applies the NEQ predicate on the "image_input_price" field.
func ImageInputPriceNEQ(v float64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldNEQ(FieldImageInputPrice, v))
}

// ImageInputPriceIn applies the In predicate on the "image_input_price" field.
func ImageInputPriceIn(vs ...float64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldIn(FieldImageInputPrice, vs...))
}

// ImageInputPriceNotIn applies the NotIn predicate on the "image_input_price" field.
func ImageInputPriceNotIn(vs ...float64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldNotIn(FieldImageInputPrice, vs...))
}

// ImageInputPriceGT applies the GT predicate on the "image_input_price" field.
func ImageInputPriceGT(v float64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldGT(FieldImageInputPrice, v))
}

// ImageInputPriceGTE applies the GTE predicate on the "image_input_price" field.
func ImageInputPriceGTE(v float64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldGTE(FieldImageInputPrice, v))
}

// ImageInputPriceLT applies the LT predicate on the "image_input_price" field.
func ImageInputPriceLT(v float64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldLT(FieldImageInputPrice, v))
}

// ImageInputPriceLTE applies the LTE predicate on the "image_input_price" field.
func ImageInputPriceLTE(v float64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldLTE(FieldImageInputPrice, v))
}

// ImageInputPriceIsNil applies the IsNil predicate on the "image_input_price" field.
func ImageInputPriceIsNil() predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldIsNull(FieldImageInputPrice))
}

// ImageInputPriceNotNil applies the NotNil predicate on the "image_input_price" field.
func ImageInputPriceNotNil() predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldNotNull(FieldImageInputPrice))
}

// ImageOutputPriceEQ applies the EQ predicate on the "image_output_price" field.
func ImageOutputPriceEQ(v float64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldEQ(FieldImageOutputPrice, v))
}

// ImageOutputPriceNEQ applies the NEQ predicate on the "image_output_price" field.
func ImageOutputPriceNEQ(v float64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldNEQ(FieldImageOutputPrice, v))
}

// ImageOutputPriceIn applies the In predicate on the "image_output_price" field.
func ImageOutputPriceIn(vs ...float64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldIn(FieldImageOutputPrice, vs...))
}

// ImageOutputPriceNotIn applies the NotIn predicate on the "image_output_price" field.
func ImageOutputPriceNotIn(vs ...float64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldNotIn(FieldImageOutputPrice, vs...))
}

// ImageOutputPriceGT applies the GT predicate on the "image_output_price" field.
func ImageOutputPriceGT(v float64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldGT(FieldImageOutputPrice, v))
}

// ImageOutputPriceGTE applies the GTE predicate on the "image_output_price" field.
func ImageOutputPriceGTE(v float64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldGTE(FieldImageOutputPrice, v))
}

// ImageOutputPriceLT applies the LT predicate on the "image_output_price" field.
func ImageOutputPriceLT(v float64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldLT(FieldImageOutputPrice, v))
}

// ImageOutputPriceLTE applies the LTE predicate on the "image_output_price" field.
func ImageOutputPriceLTE(v float64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldLTE(FieldImageOutputPrice, v))
}

// ImageOutputPriceIsNil applies the IsNil predicate on the "image_output_price" field.
func ImageOutputPriceIsNil() predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldIsNull(FieldImageOutputPrice))
}

// ImageOutputPriceNotNil applies the NotNil predicate on the "image_output_price" field.
func ImageOutputPriceNotNil() predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldNotNull(FieldImageOutputPrice))
}

// PerRequestPriceEQ applies the EQ predicate on the "per_request_price" field.
func PerRequestPriceEQ(v float64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldEQ(FieldPerRequestPrice, v))
}

// PerRequestPriceNEQ applies the NEQ predicate on the "per_request_price" field.
func PerRequestPriceNEQ(v float64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldNEQ(FieldPerRequestPrice, v))
}

// PerRequestPriceIn applies the In predicate on the "per_request_price" field.
func PerRequestPriceIn(vs ...float64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldIn(FieldPerRequestPrice, vs...))
}

// PerRequestPriceNotIn applies the NotIn predicate on the "per_request_price" field.
func PerRequestPriceNotIn(vs ...float64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldNotIn(FieldPerRequestPrice, vs...))
}

// PerRequestPriceGT applies the GT predicate on the "per_request_price" field.
func PerRequestPriceGT(v float64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldGT(FieldPerRequestPrice, v))
}

// PerRequestPriceGTE applies the GTE predicate on the "per_request_price" field.
func PerRequestPriceGTE(v float64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldGTE(FieldPerRequestPrice, v))
}

// PerRequestPriceLT applies the LT predicate on the "per_request_price" field.
func PerRequestPriceLT(v float64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldLT(FieldPerRequestPrice, v))
}

// PerRequestPriceLTE applies the LTE predicate on the "per_request_price" field.
func PerRequestPriceLTE(v float64) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldLTE(FieldPerRequestPrice, v))
}

// PerRequestPriceIsNil applies the IsNil predicate on the "per_request_price" field.
func PerRequestPriceIsNil() predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldIsNull(FieldPerRequestPrice))
}

// PerRequestPriceNotNil applies the NotNil predicate on the "per_request_price" field.
func PerRequestPriceNotNil() predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldNotNull(FieldPerRequestPrice))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.FieldContainsFold(FieldStatus, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ModelPricingOverride) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ModelPricingOverride) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ModelPricingOverride) predicate.ModelPricingOverride {
	return predicate.ModelPricingOverride(sql.NotPredicates(p))
}
