// Code generated by ent, DO NOT EDIT.

package redeemcode

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the redeemcode type in the database.
	Label = "redeem_code"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCode holds the string denoting the code field in the database.
	FieldCode = "code"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldValue holds the string denoting the value field in the database.
	FieldValue = "value"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldUsedBy holds the string denoting the used_by field in the database.
	FieldUsedBy = "used_by"
	// FieldUsedAt holds the string denoting the used_at field in the database.
	FieldUsedAt = "used_at"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldSubscriptionPlanID holds the string denoting the subscription_plan_id field in the database.
	FieldSubscriptionPlanID = "subscription_plan_id"
	// FieldPlanNameSnapshot holds the string denoting the plan_name_snapshot field in the database.
	FieldPlanNameSnapshot = "plan_name_snapshot"
	// FieldDailyLimitUsdSnapshot holds the string denoting the daily_limit_usd_snapshot field in the database.
	FieldDailyLimitUsdSnapshot = "daily_limit_usd_snapshot"
	// FieldWeeklyLimitUsdSnapshot holds the string denoting the weekly_limit_usd_snapshot field in the database.
	FieldWeeklyLimitUsdSnapshot = "weekly_limit_usd_snapshot"
	// FieldMonthlyLimitUsdSnapshot holds the string denoting the monthly_limit_usd_snapshot field in the database.
	FieldMonthlyLimitUsdSnapshot = "monthly_limit_usd_snapshot"
	// FieldRateMultiplierSnapshot holds the string denoting the rate_multiplier_snapshot field in the database.
	FieldRateMultiplierSnapshot = "rate_multiplier_snapshot"
	// FieldValidityDays holds the string denoting the validity_days field in the database.
	FieldValidityDays = "validity_days"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeSubscriptionPlan holds the string denoting the subscription_plan edge name in mutations.
	EdgeSubscriptionPlan = "subscription_plan"
	// Table holds the table name of the redeemcode in the database.
	Table = "redeem_codes"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "redeem_codes"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "used_by"
	// SubscriptionPlanTable is the table that holds the subscription_plan relation/edge.
	SubscriptionPlanTable = "redeem_codes"
	// SubscriptionPlanInverseTable is the table name for the SubscriptionPlan entity.
	// It exists in this package in order to avoid circular dependency with the "subscriptionplan" package.
	SubscriptionPlanInverseTable = "subscription_plans"
	// SubscriptionPlanColumn is the table column denoting the subscription_plan relation/edge.
	SubscriptionPlanColumn = "subscription_plan_id"
)

// Columns holds all SQL columns for redeemcode fields.
var Columns = []string{
	FieldID,
	FieldCode,
	FieldType,
	FieldValue,
	FieldStatus,
	FieldUsedBy,
	FieldUsedAt,
	FieldNotes,
	FieldCreatedAt,
	FieldExpiresAt,
	FieldSubscriptionPlanID,
	FieldPlanNameSnapshot,
	FieldDailyLimitUsdSnapshot,
	FieldWeeklyLimitUsdSnapshot,
	FieldMonthlyLimitUsdSnapshot,
	FieldRateMultiplierSnapshot,
	FieldValidityDays,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// CodeValidator is a validator for the "code" field. It is called by the builders before save.
	CodeValidator func(string) error
	// DefaultType holds the default value on creation for the "type" field.
	DefaultType string
	// TypeValidator is a validator for the "type" field. It is called by the builders before save.
	TypeValidator func(string) error
	// DefaultValue holds the default value on creation for the "value" field.
	DefaultValue float64
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultPlanNameSnapshot holds the default value on creation for the "plan_name_snapshot" field.
	DefaultPlanNameSnapshot string
	// PlanNameSnapshotValidator is a validator for the "plan_name_snapshot" field. It is called by the builders before save.
	PlanNameSnapshotValidator func(string) error
	// DefaultRateMultiplierSnapshot holds the default value on creation for the "rate_multiplier_snapshot" field.
	DefaultRateMultiplierSnapshot float64
	// DefaultValidityDays holds the default value on creation for the "validity_days" field.
	DefaultValidityDays int
)

// OrderOption defines the ordering options for the RedeemCode queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCode orders the results by the code field.
func ByCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCode, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByValue orders the results by the value field.
func ByValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValue, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByUsedBy orders the results by the used_by field.
func ByUsedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsedBy, opts...).ToFunc()
}

// ByUsedAt orders the results by the used_at field.
func ByUsedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsedAt, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// BySubscriptionPlanID orders the results by the subscription_plan_id field.
func BySubscriptionPlanID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubscriptionPlanID, opts...).ToFunc()
}

// ByPlanNameSnapshot orders the results by the plan_name_snapshot field.
func ByPlanNameSnapshot(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlanNameSnapshot, opts...).ToFunc()
}

// ByDailyLimitUsdSnapshot orders the results by the daily_limit_usd_snapshot field.
func ByDailyLimitUsdSnapshot(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDailyLimitUsdSnapshot, opts...).ToFunc()
}

// ByWeeklyLimitUsdSnapshot orders the results by the weekly_limit_usd_snapshot field.
func ByWeeklyLimitUsdSnapshot(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWeeklyLimitUsdSnapshot, opts...).ToFunc()
}

// ByMonthlyLimitUsdSnapshot orders the results by the monthly_limit_usd_snapshot field.
func ByMonthlyLimitUsdSnapshot(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMonthlyLimitUsdSnapshot, opts...).ToFunc()
}

// ByRateMultiplierSnapshot orders the results by the rate_multiplier_snapshot field.
func ByRateMultiplierSnapshot(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRateMultiplierSnapshot, opts...).ToFunc()
}

// ByValidityDays orders the results by the validity_days field.
func ByValidityDays(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValidityDays, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// BySubscriptionPlanField orders the results by subscription_plan field.
func BySubscriptionPlanField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSubscriptionPlanStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newSubscriptionPlanStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SubscriptionPlanInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SubscriptionPlanTable, SubscriptionPlanColumn),
	)
}
