// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/modelpricingoverride"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ModelPricingOverrideDelete is the builder for deleting a ModelPricingOverride entity.
type ModelPricingOverrideDelete struct {
	config
	hooks    []Hook
	mutation *ModelPricingOverrideMutation
}

// Where appends a list predicates to the ModelPricingOverrideDelete builder.
func (_d *ModelPricingOverrideDelete) Where(ps ...predicate.ModelPricingOverride) *ModelPricingOverrideDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ModelPricingOverrideDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ModelPricingOverrideDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ModelPricingOverrideDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(modelpricingoverride.Table, sqlgraph.NewFieldSpec(modelpricingoverride.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ModelPricingOverrideDeleteOne is the builder for deleting a single ModelPricingOverride entity.
type ModelPricingOverrideDeleteOne struct {
	_d *ModelPricingOverrideDelete
}

// Where appends a list predicates to the ModelPricingOverrideDelete builder.
func (_d *ModelPricingOverrideDeleteOne) Where(ps ...predicate.ModelPricingOverride) *ModelPricingOverrideDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ModelPricingOverrideDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{modelpricingoverride.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ModelPricingOverrideDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
