// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/modelpricingoverride"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/internal/domain"
)

// ModelPricingOverrideUpdate is the builder for updating ModelPricingOverride entities.
type ModelPricingOverrideUpdate struct {
	config
	hooks    []Hook
	mutation *ModelPricingOverrideMutation
}

// Where appends a list predicates to the ModelPricingOverrideUpdate builder.
func (_u *ModelPricingOverrideUpdate) Where(ps ...predicate.ModelPricingOverride) *ModelPricingOverrideUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAdapter sets the "adapter" field.
func (_u *ModelPricingOverrideUpdate) SetAdapter(v string) *ModelPricingOverrideUpdate {
	_u.mutation.SetAdapter(v)
	return _u
}

// SetNillableAdapter sets the "adapter" field if the given value is not nil.
func (_u *ModelPricingOverrideUpdate) SetNillableAdapter(v *string) *ModelPricingOverrideUpdate {
	if v != nil {
		_u.SetAdapter(*v)
	}
	return _u
}

// SetModelPattern sets the "model_pattern" field.
func (_u *ModelPricingOverrideUpdate) SetModelPattern(v string) *ModelPricingOverrideUpdate {
	_u.mutation.SetModelPattern(v)
	return _u
}

// SetNillableModelPattern sets the "model_pattern" field if the given value is not nil.
func (_u *ModelPricingOverrideUpdate) SetNillableModelPattern(v *string) *ModelPricingOverrideUpdate {
	if v != nil {
		_u.SetModelPattern(*v)
	}
	return _u
}

// SetBillingMode sets the "billing_mode" field.
func (_u *ModelPricingOverrideUpdate) SetBillingMode(v string) *ModelPricingOverrideUpdate {
	_u.mutation.SetBillingMode(v)
	return _u
}

// SetNillableBillingMode sets the "billing_mode" field if the given value is not nil.
func (_u *ModelPricingOverrideUpdate) SetNillableBillingMode(v *string) *ModelPricingOverrideUpdate {
	if v != nil {
		_u.SetBillingMode(*v)
	}
	return _u
}

// SetInputPrice sets the "input_price" field.
func (_u *ModelPricingOverrideUpdate) SetInputPrice(v float64) *ModelPricingOverrideUpdate {
	_u.mutation.ResetInputPrice()
	_u.mutation.SetInputPrice(v)
	return _u
}

// SetNillableInputPrice sets the "input_price" field if the given value is not nil.
func (_u *ModelPricingOverrideUpdate) SetNillableInputPrice(v *float64) *ModelPricingOverrideUpdate {
	if v != nil {
		_u.SetInputPrice(*v)
	}
	return _u
}

// AddInputPrice adds value to the "input_price" field.
func (_u *ModelPricingOverrideUpdate) AddInputPrice(v float64) *ModelPricingOverrideUpdate {
	_u.mutation.AddInputPrice(v)
	return _u
}

// ClearInputPrice clears the value of the "input_price" field.
func (_u *ModelPricingOverrideUpdate) ClearInputPrice() *ModelPricingOverrideUpdate {
	_u.mutation.ClearInputPrice()
	return _u
}

// SetOutputPrice sets the "output_price" field.
func (_u *ModelPricingOverrideUpdate) SetOutputPrice(v float64) *ModelPricingOverrideUpdate {
	_u.mutation.ResetOutputPrice()
	_u.mutation.SetOutputPrice(v)
	return _u
}

// SetNillableOutputPrice sets the "output_price" field if the given value is not nil.
func (_u *ModelPricingOverrideUpdate) SetNillableOutputPrice(v *float64) *ModelPricingOverrideUpdate {
	if v != nil {
		_u.SetOutputPrice(*v)
	}
	return _u
}

// AddOutputPrice adds value to the "output_price" field.
func (_u *ModelPricingOverrideUpdate) AddOutputPrice(v float64) *ModelPricingOverrideUpdate {
	_u.mutation.AddOutputPrice(v)
	return _u
}

// ClearOutputPrice clears the value of the "output_price" field.
func (_u *ModelPricingOverrideUpdate) ClearOutputPrice() *ModelPricingOverrideUpdate {
	_u.mutation.ClearOutputPrice()
	return _u
}

// SetCacheWritePrice sets the "cache_write_price" field.
func (_u *ModelPricingOverrideUpdate) SetCacheWritePrice(v float64) *ModelPricingOverrideUpdate {
	_u.mutation.ResetCacheWritePrice()
	_u.mutation.SetCacheWritePrice(v)
	return _u
}

// SetNillableCacheWritePrice sets the "cache_write_price" field if the given value is not nil.
func (_u *ModelPricingOverrideUpdate) SetNillableCacheWritePrice(v *float64) *ModelPricingOverrideUpdate {
	if v != nil {
		_u.SetCacheWritePrice(*v)
	}
	return _u
}

// AddCacheWritePrice adds value to the "cache_write_price" field.
func (_u *ModelPricingOverrideUpdate) AddCacheWritePrice(v float64) *ModelPricingOverrideUpdate {
	_u.mutation.AddCacheWritePrice(v)
	return _u
}

// ClearCacheWritePrice clears the value of the "cache_write_price" field.
func (_u *ModelPricingOverrideUpdate) ClearCacheWritePrice() *ModelPricingOverrideUpdate {
	_u.mutation.ClearCacheWritePrice()
	return _u
}

// SetCacheReadPrice sets the "cache_read_price" field.
func (_u *ModelPricingOverrideUpdate) SetCacheReadPrice(v float64) *ModelPricingOverrideUpdate {
	_u.mutation.ResetCacheReadPrice()
	_u.mutation.SetCacheReadPrice(v)
	return _u
}

// SetNillableCacheReadPrice sets the "cache_read_price" field if the given value is not nil.
func (_u *ModelPricingOverrideUpdate) SetNillableCacheReadPrice(v *float64) *ModelPricingOverrideUpdate {
	if v != nil {
		_u.SetCacheReadPrice(*v)
	}
	return _u
}

// AddCacheReadPrice adds value to the "cache_read_price" field.
func (_u *ModelPricingOverrideUpdate) AddCacheReadPrice(v float64) *ModelPricingOverrideUpdate {
	_u.mutation.AddCacheReadPrice(v)
	return _u
}

// ClearCacheReadPrice clears the value of the "cache_read_price" field.
func (_u *ModelPricingOverrideUpdate) ClearCacheReadPrice() *ModelPricingOverrideUpdate {
	_u.mutation.ClearCacheReadPrice()
	return _u
}

// SetImageInputPrice sets the "image_input_price" field.
func (_u *ModelPricingOverrideUpdate) SetImageInputPrice(v float64) *ModelPricingOverrideUpdate {
	_u.mutation.ResetImageInputPrice()
	_u.mutation.SetImageInputPrice(v)
	return _u
}

// SetNillableImageInputPrice sets the "image_input_price" field if the given value is not nil.
func (_u *ModelPricingOverrideUpdate) SetNillableImageInputPrice(v *float64) *ModelPricingOverrideUpdate {
	if v != nil {
		_u.SetImageInputPrice(*v)
	}
	return _u
}

// AddImageInputPrice adds value to the "image_input_price" field.
func (_u *ModelPricingOverrideUpdate) AddImageInputPrice(v float64) *ModelPricingOverrideUpdate {
	_u.mutation.AddImageInputPrice(v)
	return _u
}

// ClearImageInputPrice clears the value of the "image_input_price" field.
func (_u *ModelPricingOverrideUpdate) ClearImageInputPrice() *ModelPricingOverrideUpdate {
	_u.mutation.ClearImageInputPrice()
	return _u
}

// SetImageOutputPrice sets the "image_output_price" field.
func (_u *ModelPricingOverrideUpdate) SetImageOutputPrice(v float64) *ModelPricingOverrideUpdate {
	_u.mutation.ResetImageOutputPrice()
	_u.mutation.SetImageOutputPrice(v)
	return _u
}

// SetNillableImageOutputPrice sets the "image_output_price" field if the given value is not nil.
func (_u *ModelPricingOverrideUpdate) SetNillableImageOutputPrice(v *float64) *ModelPricingOverrideUpdate {
	if v != nil {
		_u.SetImageOutputPrice(*v)
	}
	return _u
}

// AddImageOutputPrice adds value to the "image_output_price" field.
func (_u *ModelPricingOverrideUpdate) AddImageOutputPrice(v float64) *ModelPricingOverrideUpdate {
	_u.mutation.AddImageOutputPrice(v)
	return _u
}

// ClearImageOutputPrice clears the value of the "image_output_price" field.
func (_u *ModelPricingOverrideUpdate) ClearImageOutputPrice() *ModelPricingOverrideUpdate {
	_u.mutation.ClearImageOutputPrice()
	return _u
}

// SetPerRequestPrice sets the "per_request_price" field.
func (_u *ModelPricingOverrideUpdate) SetPerRequestPrice(v float64) *ModelPricingOverrideUpdate {
	_u.mutation.ResetPerRequestPrice()
	_u.mutation.SetPerRequestPrice(v)
	return _u
}

// SetNillablePerRequestPrice sets the "per_request_price" field if the given value is not nil.
func (_u *ModelPricingOverrideUpdate) SetNillablePerRequestPrice(v *float64) *ModelPricingOverrideUpdate {
	if v != nil {
		_u.SetPerRequestPrice(*v)
	}
	return _u
}

// AddPerRequestPrice adds value to the "per_request_price" field.
func (_u *ModelPricingOverrideUpdate) AddPerRequestPrice(v float64) *ModelPricingOverrideUpdate {
	_u.mutation.AddPerRequestPrice(v)
	return _u
}

// ClearPerRequestPrice clears the value of the "per_request_price" field.
func (_u *ModelPricingOverrideUpdate) ClearPerRequestPrice() *ModelPricingOverrideUpdate {
	_u.mutation.ClearPerRequestPrice()
	return _u
}

// SetIntervals sets the "intervals" field.
func (_u *ModelPricingOverrideUpdate) SetIntervals(v []domain.ModelPricingInterval) *ModelPricingOverrideUpdate {
	_u.mutation.SetIntervals(v)
	return _u
}

// AppendIntervals appends value to the "intervals" field.
func (_u *ModelPricingOverrideUpdate) AppendIntervals(v []domain.ModelPricingInterval) *ModelPricingOverrideUpdate {
	_u.mutation.AppendIntervals(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *ModelPricingOverrideUpdate) SetStatus(v string) *ModelPricingOverrideUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ModelPricingOverrideUpdate) SetNillableStatus(v *string) *ModelPricingOverrideUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// Mutation returns the ModelPricingOverrideMutation object of the builder.
func (_u *ModelPricingOverrideUpdate) Mutation() *ModelPricingOverrideMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ModelPricingOverrideUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelPricingOverrideUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ModelPricingOverrideUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelPricingOverrideUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModelPricingOverrideUpdate) check() error {
	if v, ok := _u.mutation.Adapter(); ok {
		if err := modelpricingoverride.AdapterValidator(v); err != nil {
			return &ValidationError{Name: "adapter", err: fmt.Errorf(`ent: validator failed for field "ModelPricingOverride.adapter": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ModelPattern(); ok {
		if err := modelpricingoverride.ModelPatternValidator(v); err != nil {
			return &ValidationError{Name: "model_pattern", err: fmt.Errorf(`ent: validator failed for field "ModelPricingOverride.model_pattern": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BillingMode(); ok {
		if err := modelpricingoverride.BillingModeValidator(v); err != nil {
			return &ValidationError{Name: "billing_mode", err: fmt.Errorf(`ent: validator failed for field "ModelPricingOverride.billing_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := modelpricingoverride.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ModelPricingOverride.status": %w`, err)}
		}
	}
	return nil
}

func (_u *ModelPricingOverrideUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(modelpricingoverride.Table, modelpricingoverride.Columns, sqlgraph.NewFieldSpec(modelpricingoverride.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Adapter(); ok {
		_spec.SetField(modelpricingoverride.FieldAdapter, field.TypeString, value)
	}
	if value, ok := _u.mutation.ModelPattern(); ok {
		_spec.SetField(modelpricingoverride.FieldModelPattern, field.TypeString, value)
	}
	if value, ok := _u.mutation.BillingMode(); ok {
		_spec.SetField(modelpricingoverride.FieldBillingMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.InputPrice(); ok {
		_spec.SetField(modelpricingoverride.FieldInputPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedInputPrice(); ok {
		_spec.AddField(modelpricingoverride.FieldInputPrice, field.TypeFloat64, value)
	}
	if _u.mutation.InputPriceCleared() {
		_spec.ClearField(modelpricingoverride.FieldInputPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.OutputPrice(); ok {
		_spec.SetField(modelpricingoverride.FieldOutputPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOutputPrice(); ok {
		_spec.AddField(modelpricingoverride.FieldOutputPrice, field.TypeFloat64, value)
	}
	if _u.mutation.OutputPriceCleared() {
		_spec.ClearField(modelpricingoverride.FieldOutputPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CacheWritePrice(); ok {
		_spec.SetField(modelpricingoverride.FieldCacheWritePrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCacheWritePrice(); ok {
		_spec.AddField(modelpricingoverride.FieldCacheWritePrice, field.TypeFloat64, value)
	}
	if _u.mutation.CacheWritePriceCleared() {
		_spec.ClearField(modelpricingoverride.FieldCacheWritePrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CacheReadPrice(); ok {
		_spec.SetField(modelpricingoverride.FieldCacheReadPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCacheReadPrice(); ok {
		_spec.AddField(modelpricingoverride.FieldCacheReadPrice, field.TypeFloat64, value)
	}
	if _u.mutation.CacheReadPriceCleared() {
		_spec.ClearField(modelpricingoverride.FieldCacheReadPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ImageInputPrice(); ok {
		_spec.SetField(modelpricingoverride.FieldImageInputPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedImageInputPrice(); ok {
		_spec.AddField(modelpricingoverride.FieldImageInputPrice, field.TypeFloat64, value)
	}
	if _u.mutation.ImageInputPriceCleared() {
		_spec.ClearField(modelpricingoverride.FieldImageInputPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ImageOutputPrice(); ok {
		_spec.SetField(modelpricingoverride.FieldImageOutputPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedImageOutputPrice(); ok {
		_spec.AddField(modelpricingoverride.FieldImageOutputPrice, field.TypeFloat64, value)
	}
	if _u.mutation.ImageOutputPriceCleared() {
		_spec.ClearField(modelpricingoverride.FieldImageOutputPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.PerRequestPrice(); ok {
		_spec.SetField(modelpricingoverride.FieldPerRequestPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPerRequestPrice(); ok {
		_spec.AddField(modelpricingoverride.FieldPerRequestPrice, field.TypeFloat64, value)
	}
	if _u.mutation.PerRequestPriceCleared() {
		_spec.ClearField(modelpricingoverride.FieldPerRequestPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Intervals(); ok {
		_spec.SetField(modelpricingoverride.FieldIntervals, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedIntervals(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, modelpricingoverride.FieldIntervals, value)
		})
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(modelpricingoverride.FieldStatus, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modelpricingoverride.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ModelPricingOverrideUpdateOne is the builder for updating a single ModelPricingOverride entity.
type ModelPricingOverrideUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ModelPricingOverrideMutation
}

// SetAdapter sets the "adapter" field.
func (_u *ModelPricingOverrideUpdateOne) SetAdapter(v string) *ModelPricingOverrideUpdateOne {
	_u.mutation.SetAdapter(v)
	return _u
}

// SetNillableAdapter sets the "adapter" field if the given value is not nil.
func (_u *ModelPricingOverrideUpdateOne) SetNillableAdapter(v *string) *ModelPricingOverrideUpdateOne {
	if v != nil {
		_u.SetAdapter(*v)
	}
	return _u
}

// SetModelPattern sets the "model_pattern" field.
func (_u *ModelPricingOverrideUpdateOne) SetModelPattern(v string) *ModelPricingOverrideUpdateOne {
	_u.mutation.SetModelPattern(v)
	return _u
}

// SetNillableModelPattern sets the "model_pattern" field if the given value is not nil.
func (_u *ModelPricingOverrideUpdateOne) SetNillableModelPattern(v *string) *ModelPricingOverrideUpdateOne {
	if v != nil {
		_u.SetModelPattern(*v)
	}
	return _u
}

// SetBillingMode sets the "billing_mode" field.
func (_u *ModelPricingOverrideUpdateOne) SetBillingMode(v string) *ModelPricingOverrideUpdateOne {
	_u.mutation.SetBillingMode(v)
	return _u
}

// SetNillableBillingMode sets the "billing_mode" field if the given value is not nil.
func (_u *ModelPricingOverrideUpdateOne) SetNillableBillingMode(v *string) *ModelPricingOverrideUpdateOne {
	if v != nil {
		_u.SetBillingMode(*v)
	}
	return _u
}

// SetInputPrice sets the "input_price" field.
func (_u *ModelPricingOverrideUpdateOne) SetInputPrice(v float64) *ModelPricingOverrideUpdateOne {
	_u.mutation.ResetInputPrice()
	_u.mutation.SetInputPrice(v)
	return _u
}

// SetNillableInputPrice sets the "input_price" field if the given value is not nil.
func (_u *ModelPricingOverrideUpdateOne) SetNillableInputPrice(v *float64) *ModelPricingOverrideUpdateOne {
	if v != nil {
		_u.SetInputPrice(*v)
	}
	return _u
}

// AddInputPrice adds value to the "input_price" field.
func (_u *ModelPricingOverrideUpdateOne) AddInputPrice(v float64) *ModelPricingOverrideUpdateOne {
	_u.mutation.AddInputPrice(v)
	return _u
}

// ClearInputPrice clears the value of the "input_price" field.
func (_u *ModelPricingOverrideUpdateOne) ClearInputPrice() *ModelPricingOverrideUpdateOne {
	_u.mutation.ClearInputPrice()
	return _u
}

// SetOutputPrice sets the "output_price" field.
func (_u *ModelPricingOverrideUpdateOne) SetOutputPrice(v float64) *ModelPricingOverrideUpdateOne {
	_u.mutation.ResetOutputPrice()
	_u.mutation.SetOutputPrice(v)
	return _u
}

// SetNillableOutputPrice sets the "output_price" field if the given value is not nil.
func (_u *ModelPricingOverrideUpdateOne) SetNillableOutputPrice(v *float64) *ModelPricingOverrideUpdateOne {
	if v != nil {
		_u.SetOutputPrice(*v)
	}
	return _u
}

// AddOutputPrice adds value to the "output_price" field.
func (_u *ModelPricingOverrideUpdateOne) AddOutputPrice(v float64) *ModelPricingOverrideUpdateOne {
	_u.mutation.AddOutputPrice(v)
	return _u
}

// ClearOutputPrice clears the value of the "output_price" field.
func (_u *ModelPricingOverrideUpdateOne) ClearOutputPrice() *ModelPricingOverrideUpdateOne {
	_u.mutation.ClearOutputPrice()
	return _u
}

// SetCacheWritePrice sets the "cache_write_price" field.
func (_u *ModelPricingOverrideUpdateOne) SetCacheWritePrice(v float64) *ModelPricingOverrideUpdateOne {
	_u.mutation.ResetCacheWritePrice()
	_u.mutation.SetCacheWritePrice(v)
	return _u
}

// SetNillableCacheWritePrice sets the "cache_write_price" field if the given value is not nil.
func (_u *ModelPricingOverrideUpdateOne) SetNillableCacheWritePrice(v *float64) *ModelPricingOverrideUpdateOne {
	if v != nil {
		_u.SetCacheWritePrice(*v)
	}
	return _u
}

// AddCacheWritePrice adds value to the "cache_write_price" field.
func (_u *ModelPricingOverrideUpdateOne) AddCacheWritePrice(v float64) *ModelPricingOverrideUpdateOne {
	_u.mutation.AddCacheWritePrice(v)
	return _u
}

// ClearCacheWritePrice clears the value of the "cache_write_price" field.
func (_u *ModelPricingOverrideUpdateOne) ClearCacheWritePrice() *ModelPricingOverrideUpdateOne {
	_u.mutation.ClearCacheWritePrice()
	return _u
}

// SetCacheReadPrice sets the "cache_read_price" field.
func (_u *ModelPricingOverrideUpdateOne) SetCacheReadPrice(v float64) *ModelPricingOverrideUpdateOne {
	_u.mutation.ResetCacheReadPrice()
	_u.mutation.SetCacheReadPrice(v)
	return _u
}

// SetNillableCacheReadPrice sets the "cache_read_price" field if the given value is not nil.
func (_u *ModelPricingOverrideUpdateOne) SetNillableCacheReadPrice(v *float64) *ModelPricingOverrideUpdateOne {
	if v != nil {
		_u.SetCacheReadPrice(*v)
	}
	return _u
}

// AddCacheReadPrice adds value to the "cache_read_price" field.
func (_u *ModelPricingOverrideUpdateOne) AddCacheReadPrice(v float64) *ModelPricingOverrideUpdateOne {
	_u.mutation.AddCacheReadPrice(v)
	return _u
}

// ClearCacheReadPrice clears the value of the "cache_read_price" field.
func (_u *ModelPricingOverrideUpdateOne) ClearCacheReadPrice() *ModelPricingOverrideUpdateOne {
	_u.mutation.ClearCacheReadPrice()
	return _u
}

// SetImageInputPrice sets the "image_input_price" field.
func (_u *ModelPricingOverrideUpdateOne) SetImageInputPrice(v float64) *ModelPricingOverrideUpdateOne {
	_u.mutation.ResetImageInputPrice()
	_u.mutation.SetImageInputPrice(v)
	return _u
}

// SetNillableImageInputPrice sets the "image_input_price" field if the given value is not nil.
func (_u *ModelPricingOverrideUpdateOne) SetNillableImageInputPrice(v *float64) *ModelPricingOverrideUpdateOne {
	if v != nil {
		_u.SetImageInputPrice(*v)
	}
	return _u
}

// AddImageInputPrice adds value to the "image_input_price" field.
func (_u *ModelPricingOverrideUpdateOne) AddImageInputPrice(v float64) *ModelPricingOverrideUpdateOne {
	_u.mutation.AddImageInputPrice(v)
	return _u
}

// ClearImageInputPrice clears the value of the "image_input_price" field.
func (_u *ModelPricingOverrideUpdateOne) ClearImageInputPrice() *ModelPricingOverrideUpdateOne {
	_u.mutation.ClearImageInputPrice()
	return _u
}

// SetImageOutputPrice sets the "image_output_price" field.
func (_u *ModelPricingOverrideUpdateOne) SetImageOutputPrice(v float64) *ModelPricingOverrideUpdateOne {
	_u.mutation.ResetImageOutputPrice()
	_u.mutation.SetImageOutputPrice(v)
	return _u
}

// SetNillableImageOutputPrice sets the "image_output_price" field if the given value is not nil.
func (_u *ModelPricingOverrideUpdateOne) SetNillableImageOutputPrice(v *float64) *ModelPricingOverrideUpdateOne {
	if v != nil {
		_u.SetImageOutputPrice(*v)
	}
	return _u
}

// AddImageOutputPrice adds value to the "image_output_price" field.
func (_u *ModelPricingOverrideUpdateOne) AddImageOutputPrice(v float64) *ModelPricingOverrideUpdateOne {
	_u.mutation.AddImageOutputPrice(v)
	return _u
}

// ClearImageOutputPrice clears the value of the "image_output_price" field.
func (_u *ModelPricingOverrideUpdateOne) ClearImageOutputPrice() *ModelPricingOverrideUpdateOne {
	_u.mutation.ClearImageOutputPrice()
	return _u
}

// SetPerRequestPrice sets the "per_request_price" field.
func (_u *ModelPricingOverrideUpdateOne) SetPerRequestPrice(v float64) *ModelPricingOverrideUpdateOne {
	_u.mutation.ResetPerRequestPrice()
	_u.mutation.SetPerRequestPrice(v)
	return _u
}

// SetNillablePerRequestPrice sets the "per_request_price" field if the given value is not nil.
func (_u *ModelPricingOverrideUpdateOne) SetNillablePerRequestPrice(v *float64) *ModelPricingOverrideUpdateOne {
	if v != nil {
		_u.SetPerRequestPrice(*v)
	}
	return _u
}

// AddPerRequestPrice adds value to the "per_request_price" field.
func (_u *ModelPricingOverrideUpdateOne) AddPerRequestPrice(v float64) *ModelPricingOverrideUpdateOne {
	_u.mutation.AddPerRequestPrice(v)
	return _u
}

// ClearPerRequestPrice clears the value of the "per_request_price" field.
func (_u *ModelPricingOverrideUpdateOne) ClearPerRequestPrice() *ModelPricingOverrideUpdateOne {
	_u.mutation.ClearPerRequestPrice()
	return _u
}

// SetIntervals sets the "intervals" field.
func (_u *ModelPricingOverrideUpdateOne) SetIntervals(v []domain.ModelPricingInterval) *ModelPricingOverrideUpdateOne {
	_u.mutation.SetIntervals(v)
	return _u
}

// AppendIntervals appends value to the "intervals" field.
func (_u *ModelPricingOverrideUpdateOne) AppendIntervals(v []domain.ModelPricingInterval) *ModelPricingOverrideUpdateOne {
	_u.mutation.AppendIntervals(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *ModelPricingOverrideUpdateOne) SetStatus(v string) *ModelPricingOverrideUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ModelPricingOverrideUpdateOne) SetNillableStatus(v *string) *ModelPricingOverrideUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// Mutation returns the ModelPricingOverrideMutation object of the builder.
func (_u *ModelPricingOverrideUpdateOne) Mutation() *ModelPricingOverrideMutation {
	return _u.mutation
}

// Where appends a list predicates to the ModelPricingOverrideUpdate builder.
func (_u *ModelPricingOverrideUpdateOne) Where(ps ...predicate.ModelPricingOverride) *ModelPricingOverrideUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ModelPricingOverrideUpdateOne) Select(field string, fields ...string) *ModelPricingOverrideUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ModelPricingOverride entity.
func (_u *ModelPricingOverrideUpdateOne) Save(ctx context.Context) (*ModelPricingOverride, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelPricingOverrideUpdateOne) SaveX(ctx context.Context) *ModelPricingOverride {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ModelPricingOverrideUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelPricingOverrideUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModelPricingOverrideUpdateOne) check() error {
	if v, ok := _u.mutation.Adapter(); ok {
		if err := modelpricingoverride.AdapterValidator(v); err != nil {
			return &ValidationError{Name: "adapter", err: fmt.Errorf(`ent: validator failed for field "ModelPricingOverride.adapter": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ModelPattern(); ok {
		if err := modelpricingoverride.ModelPatternValidator(v); err != nil {
			return &ValidationError{Name: "model_pattern", err: fmt.Errorf(`ent: validator failed for field "ModelPricingOverride.model_pattern": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BillingMode(); ok {
		if err := modelpricingoverride.BillingModeValidator(v); err != nil {
			return &ValidationError{Name: "billing_mode", err: fmt.Errorf(`ent: validator failed for field "ModelPricingOverride.billing_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := modelpricingoverride.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ModelPricingOverride.status": %w`, err)}
		}
	}
	return nil
}

func (_u *ModelPricingOverrideUpdateOne) sqlSave(ctx context.Context) (_node *ModelPricingOverride, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(modelpricingoverride.Table, modelpricingoverride.Columns, sqlgraph.NewFieldSpec(modelpricingoverride.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ModelPricingOverride.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, modelpricingoverride.FieldID)
		for _, f := range fields {
			if !modelpricingoverride.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != modelpricingoverride.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Adapter(); ok {
		_spec.SetField(modelpricingoverride.FieldAdapter, field.TypeString, value)
	}
	if value, ok := _u.mutation.ModelPattern(); ok {
		_spec.SetField(modelpricingoverride.FieldModelPattern, field.TypeString, value)
	}
	if value, ok := _u.mutation.BillingMode(); ok {
		_spec.SetField(modelpricingoverride.FieldBillingMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.InputPrice(); ok {
		_spec.SetField(modelpricingoverride.FieldInputPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedInputPrice(); ok {
		_spec.AddField(modelpricingoverride.FieldInputPrice, field.TypeFloat64, value)
	}
	if _u.mutation.InputPriceCleared() {
		_spec.ClearField(modelpricingoverride.FieldInputPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.OutputPrice(); ok {
		_spec.SetField(modelpricingoverride.FieldOutputPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOutputPrice(); ok {
		_spec.AddField(modelpricingoverride.FieldOutputPrice, field.TypeFloat64, value)
	}
	if _u.mutation.OutputPriceCleared() {
		_spec.ClearField(modelpricingoverride.FieldOutputPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CacheWritePrice(); ok {
		_spec.SetField(modelpricingoverride.FieldCacheWritePrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCacheWritePrice(); ok {
		_spec.AddField(modelpricingoverride.FieldCacheWritePrice, field.TypeFloat64, value)
	}
	if _u.mutation.CacheWritePriceCleared() {
		_spec.ClearField(modelpricingoverride.FieldCacheWritePrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CacheReadPrice(); ok {
		_spec.SetField(modelpricingoverride.FieldCacheReadPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCacheReadPrice(); ok {
		_spec.AddField(modelpricingoverride.FieldCacheReadPrice, field.TypeFloat64, value)
	}
	if _u.mutation.CacheReadPriceCleared() {
		_spec.ClearField(modelpricingoverride.FieldCacheReadPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ImageInputPrice(); ok {
		_spec.SetField(modelpricingoverride.FieldImageInputPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedImageInputPrice(); ok {
		_spec.AddField(modelpricingoverride.FieldImageInputPrice, field.TypeFloat64, value)
	}
	if _u.mutation.ImageInputPriceCleared() {
		_spec.ClearField(modelpricingoverride.FieldImageInputPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ImageOutputPrice(); ok {
		_spec.SetField(modelpricingoverride.FieldImageOutputPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedImageOutputPrice(); ok {
		_spec.AddField(modelpricingoverride.FieldImageOutputPrice, field.TypeFloat64, value)
	}
	if _u.mutation.ImageOutputPriceCleared() {
		_spec.ClearField(modelpricingoverride.FieldImageOutputPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.PerRequestPrice(); ok {
		_spec.SetField(modelpricingoverride.FieldPerRequestPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPerRequestPrice(); ok {
		_spec.AddField(modelpricingoverride.FieldPerRequestPrice, field.TypeFloat64, value)
	}
	if _u.mutation.PerRequestPriceCleared() {
		_spec.ClearField(modelpricingoverride.FieldPerRequestPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Intervals(); ok {
		_spec.SetField(modelpricingoverride.FieldIntervals, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedIntervals(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, modelpricingoverride.FieldIntervals, value)
		})
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(modelpricingoverride.FieldStatus, field.TypeString, value)
	}
	_node = &ModelPricingOverride{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modelpricingoverride.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
