// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/modelpricingoverride"
	"github.com/Wei-Shaw/sub2api/internal/domain"
)

// ModelPricingOverride is the model entity for the ModelPricingOverride schema.
type ModelPricingOverride struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// Adapter holds the value of the "adapter" field.
	Adapter string `json:"adapter,omitempty"`
	// ModelPattern holds the value of the "model_pattern" field.
	ModelPattern string `json:"model_pattern,omitempty"`
	// BillingMode holds the value of the "billing_mode" field.
	BillingMode string `json:"billing_mode,omitempty"`
	// InputPrice holds the value of the "input_price" field.
	InputPrice *float64 `json:"input_price,omitempty"`
	// OutputPrice holds the value of the "output_price" field.
	OutputPrice *float64 `json:"output_price,omitempty"`
	// CacheWritePrice holds the value of the "cache_write_price" field.
	CacheWritePrice *float64 `json:"cache_write_price,omitempty"`
	// CacheReadPrice holds the value of the "cache_read_price" field.
	CacheReadPrice *float64 `json:"cache_read_price,omitempty"`
	// ImageInputPrice holds the value of the "image_input_price" field.
	ImageInputPrice *float64 `json:"image_input_price,omitempty"`
	// ImageOutputPrice holds the value of the "image_output_price" field.
	ImageOutputPrice *float64 `json:"image_output_price,omitempty"`
	// PerRequestPrice holds the value of the "per_request_price" field.
	PerRequestPrice *float64 `json:"per_request_price,omitempty"`
	// Intervals holds the value of the "intervals" field.
	Intervals []domain.ModelPricingInterval `json:"intervals,omitempty"`
	// Status holds the value of the "status" field.
	Status       string `json:"status,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ModelPricingOverride) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case modelpricingoverride.FieldIntervals:
			values[i] = new([]byte)
		case modelpricingoverride.FieldInputPrice, modelpricingoverride.FieldOutputPrice, modelpricingoverride.FieldCacheWritePrice, modelpricingoverride.FieldCacheReadPrice, modelpricingoverride.FieldImageInputPrice, modelpricingoverride.FieldImageOutputPrice, modelpricingoverride.FieldPerRequestPrice:
			values[i] = new(sql.NullFloat64)
		case modelpricingoverride.FieldID:
			values[i] = new(sql.NullInt64)
		case modelpricingoverride.FieldAdapter, modelpricingoverride.FieldModelPattern, modelpricingoverride.FieldBillingMode, modelpricingoverride.FieldStatus:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ModelPricingOverride fields.
func (_m *ModelPricingOverride) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case modelpricingoverride.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case modelpricingoverride.FieldAdapter:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field adapter", values[i])
			} else if value.Valid {
				_m.Adapter = value.String
			}
		case modelpricingoverride.FieldModelPattern:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model_pattern", values[i])
			} else if value.Valid {
				_m.ModelPattern = value.String
			}
		case modelpricingoverride.FieldBillingMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field billing_mode", values[i])
			} else if value.Valid {
				_m.BillingMode = value.String
			}
		case modelpricingoverride.FieldInputPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field input_price", values[i])
			} else if value.Valid {
				_m.InputPrice = new(float64)
				*_m.InputPrice = value.Float64
			}
		case modelpricingoverride.FieldOutputPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field output_price", values[i])
			} else if value.Valid {
				_m.OutputPrice = new(float64)
				*_m.OutputPrice = value.Float64
			}
		case modelpricingoverride.FieldCacheWritePrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field cache_write_price", values[i])
			} else if value.Valid {
				_m.CacheWritePrice = new(float64)
				*_m.CacheWritePrice = value.Float64
			}
		case modelpricingoverride.FieldCacheReadPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field cache_read_price", values[i])
			} else if value.Valid {
				_m.CacheReadPrice = new(float64)
				*_m.CacheReadPrice = value.Float64
			}
		case modelpricingoverride.FieldImageInputPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field image_input_price", values[i])
			} else if value.Valid {
				_m.ImageInputPrice = new(float64)
				*_m.ImageInputPrice = value.Float64
			}
		case modelpricingoverride.FieldImageOutputPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field image_output_price", values[i])
			} else if value.Valid {
				_m.ImageOutputPrice = new(float64)
				*_m.ImageOutputPrice = value.Float64
			}
		case modelpricingoverride.FieldPerRequestPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field per_request_price", values[i])
			} else if value.Valid {
				_m.PerRequestPrice = new(float64)
				*_m.PerRequestPrice = value.Float64
			}
		case modelpricingoverride.FieldIntervals:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field intervals", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Intervals); err != nil {
					return fmt.Errorf("unmarshal field intervals: %w", err)
				}
			}
		case modelpricingoverride.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ModelPricingOverride.
// This includes values selected through modifiers, order, etc.
func (_m *ModelPricingOverride) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ModelPricingOverride.
// Note that you need to call ModelPricingOverride.Unwrap() before calling this method if this ModelPricingOverride
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ModelPricingOverride) Update() *ModelPricingOverrideUpdateOne {
	return NewModelPricingOverrideClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ModelPricingOverride entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ModelPricingOverride) Unwrap() *ModelPricingOverride {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ModelPricingOverride is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ModelPricingOverride) String() string {
	var builder strings.Builder
	builder.WriteString("ModelPricingOverride(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("adapter=")
	builder.WriteString(_m.Adapter)
	builder.WriteString(", ")
	builder.WriteString("model_pattern=")
	builder.WriteString(_m.ModelPattern)
	builder.WriteString(", ")
	builder.WriteString("billing_mode=")
	builder.WriteString(_m.BillingMode)
	builder.WriteString(", ")
	if v := _m.InputPrice; v != nil {
		builder.WriteString("input_price=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.OutputPrice; v != nil {
		builder.WriteString("output_price=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CacheWritePrice; v != nil {
		builder.WriteString("cache_write_price=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CacheReadPrice; v != nil {
		builder.WriteString("cache_read_price=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ImageInputPrice; v != nil {
		builder.WriteString("image_input_price=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ImageOutputPrice; v != nil {
		builder.WriteString("image_output_price=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.PerRequestPrice; v != nil {
		builder.WriteString("per_request_price=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("intervals=")
	builder.WriteString(fmt.Sprintf("%v", _m.Intervals))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteByte(')')
	return builder.String()
}

// ModelPricingOverrides is a parsable slice of ModelPricingOverride.
type ModelPricingOverrides []*ModelPricingOverride
