// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/platform"
	"github.com/Wei-Shaw/sub2api/ent/platformmodelrule"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/usagelog"
)

// PlatformUpdate is the builder for updating Platform entities.
type PlatformUpdate struct {
	config
	hooks    []Hook
	mutation *PlatformMutation
}

// Where appends a list predicates to the PlatformUpdate builder.
func (_u *PlatformUpdate) Where(ps ...predicate.Platform) *PlatformUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PlatformUpdate) SetUpdatedAt(v time.Time) *PlatformUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCode sets the "code" field.
func (_u *PlatformUpdate) SetCode(v string) *PlatformUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *PlatformUpdate) SetNillableCode(v *string) *PlatformUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *PlatformUpdate) SetName(v string) *PlatformUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PlatformUpdate) SetNillableName(v *string) *PlatformUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAccountPlatform sets the "account_platform" field.
func (_u *PlatformUpdate) SetAccountPlatform(v string) *PlatformUpdate {
	_u.mutation.SetAccountPlatform(v)
	return _u
}

// SetNillableAccountPlatform sets the "account_platform" field if the given value is not nil.
func (_u *PlatformUpdate) SetNillableAccountPlatform(v *string) *PlatformUpdate {
	if v != nil {
		_u.SetAccountPlatform(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *PlatformUpdate) SetStatus(v string) *PlatformUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PlatformUpdate) SetNillableStatus(v *string) *PlatformUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetEndpointCapabilities sets the "endpoint_capabilities" field.
func (_u *PlatformUpdate) SetEndpointCapabilities(v []string) *PlatformUpdate {
	_u.mutation.SetEndpointCapabilities(v)
	return _u
}

// AppendEndpointCapabilities appends value to the "endpoint_capabilities" field.
func (_u *PlatformUpdate) AppendEndpointCapabilities(v []string) *PlatformUpdate {
	_u.mutation.AppendEndpointCapabilities(v)
	return _u
}

// AddModelRuleIDs adds the "model_rules" edge to the PlatformModelRule entity by IDs.
func (_u *PlatformUpdate) AddModelRuleIDs(ids ...int64) *PlatformUpdate {
	_u.mutation.AddModelRuleIDs(ids...)
	return _u
}

// AddModelRules adds the "model_rules" edges to the PlatformModelRule entity.
func (_u *PlatformUpdate) AddModelRules(v ...*PlatformModelRule) *PlatformUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddModelRuleIDs(ids...)
}

// AddAccountIDs adds the "accounts" edge to the Account entity by IDs.
func (_u *PlatformUpdate) AddAccountIDs(ids ...int64) *PlatformUpdate {
	_u.mutation.AddAccountIDs(ids...)
	return _u
}

// AddAccounts adds the "accounts" edges to the Account entity.
func (_u *PlatformUpdate) AddAccounts(v ...*Account) *PlatformUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAccountIDs(ids...)
}

// AddAPIKeyIDs adds the "api_keys" edge to the APIKey entity by IDs.
func (_u *PlatformUpdate) AddAPIKeyIDs(ids ...int64) *PlatformUpdate {
	_u.mutation.AddAPIKeyIDs(ids...)
	return _u
}

// AddAPIKeys adds the "api_keys" edges to the APIKey entity.
func (_u *PlatformUpdate) AddAPIKeys(v ...*APIKey) *PlatformUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAPIKeyIDs(ids...)
}

// AddUsageLogIDs adds the "usage_logs" edge to the UsageLog entity by IDs.
func (_u *PlatformUpdate) AddUsageLogIDs(ids ...int64) *PlatformUpdate {
	_u.mutation.AddUsageLogIDs(ids...)
	return _u
}

// AddUsageLogs adds the "usage_logs" edges to the UsageLog entity.
func (_u *PlatformUpdate) AddUsageLogs(v ...*UsageLog) *PlatformUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUsageLogIDs(ids...)
}

// Mutation returns the PlatformMutation object of the builder.
func (_u *PlatformUpdate) Mutation() *PlatformMutation {
	return _u.mutation
}

// ClearModelRules clears all "model_rules" edges to the PlatformModelRule entity.
func (_u *PlatformUpdate) ClearModelRules() *PlatformUpdate {
	_u.mutation.ClearModelRules()
	return _u
}

// RemoveModelRuleIDs removes the "model_rules" edge to PlatformModelRule entities by IDs.
func (_u *PlatformUpdate) RemoveModelRuleIDs(ids ...int64) *PlatformUpdate {
	_u.mutation.RemoveModelRuleIDs(ids...)
	return _u
}

// RemoveModelRules removes "model_rules" edges to PlatformModelRule entities.
func (_u *PlatformUpdate) RemoveModelRules(v ...*PlatformModelRule) *PlatformUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveModelRuleIDs(ids...)
}

// ClearAccounts clears all "accounts" edges to the Account entity.
func (_u *PlatformUpdate) ClearAccounts() *PlatformUpdate {
	_u.mutation.ClearAccounts()
	return _u
}

// RemoveAccountIDs removes the "accounts" edge to Account entities by IDs.
func (_u *PlatformUpdate) RemoveAccountIDs(ids ...int64) *PlatformUpdate {
	_u.mutation.RemoveAccountIDs(ids...)
	return _u
}

// RemoveAccounts removes "accounts" edges to Account entities.
func (_u *PlatformUpdate) RemoveAccounts(v ...*Account) *PlatformUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAccountIDs(ids...)
}

// ClearAPIKeys clears all "api_keys" edges to the APIKey entity.
func (_u *PlatformUpdate) ClearAPIKeys() *PlatformUpdate {
	_u.mutation.ClearAPIKeys()
	return _u
}

// RemoveAPIKeyIDs removes the "api_keys" edge to APIKey entities by IDs.
func (_u *PlatformUpdate) RemoveAPIKeyIDs(ids ...int64) *PlatformUpdate {
	_u.mutation.RemoveAPIKeyIDs(ids...)
	return _u
}

// RemoveAPIKeys removes "api_keys" edges to APIKey entities.
func (_u *PlatformUpdate) RemoveAPIKeys(v ...*APIKey) *PlatformUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAPIKeyIDs(ids...)
}

// ClearUsageLogs clears all "usage_logs" edges to the UsageLog entity.
func (_u *PlatformUpdate) ClearUsageLogs() *PlatformUpdate {
	_u.mutation.ClearUsageLogs()
	return _u
}

// RemoveUsageLogIDs removes the "usage_logs" edge to UsageLog entities by IDs.
func (_u *PlatformUpdate) RemoveUsageLogIDs(ids ...int64) *PlatformUpdate {
	_u.mutation.RemoveUsageLogIDs(ids...)
	return _u
}

// RemoveUsageLogs removes "usage_logs" edges to UsageLog entities.
func (_u *PlatformUpdate) RemoveUsageLogs(v ...*UsageLog) *PlatformUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUsageLogIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PlatformUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PlatformUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PlatformUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PlatformUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PlatformUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := platform.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PlatformUpdate) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := platform.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Platform.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := platform.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Platform.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AccountPlatform(); ok {
		if err := platform.AccountPlatformValidator(v); err != nil {
			return &ValidationError{Name: "account_platform", err: fmt.Errorf(`ent: validator failed for field "Platform.account_platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := platform.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Platform.status": %w`, err)}
		}
	}
	return nil
}

func (_u *PlatformUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(platform.Table, platform.Columns, sqlgraph.NewFieldSpec(platform.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(platform.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(platform.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(platform.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountPlatform(); ok {
		_spec.SetField(platform.FieldAccountPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(platform.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.EndpointCapabilities(); ok {
		_spec.SetField(platform.FieldEndpointCapabilities, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedEndpointCapabilities(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, platform.FieldEndpointCapabilities, value)
		})
	}
	if _u.mutation.ModelRulesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   platform.ModelRulesTable,
			Columns: []string{platform.ModelRulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(platformmodelrule.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedModelRulesIDs(); len(nodes) > 0 && !_u.mutation.ModelRulesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   platform.ModelRulesTable,
			Columns: []string{platform.ModelRulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(platformmodelrule.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ModelRulesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   platform.ModelRulesTable,
			Columns: []string{platform.ModelRulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(platformmodelrule.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   platform.AccountsTable,
			Columns: []string{platform.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAccountsIDs(); len(nodes) > 0 && !_u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   platform.AccountsTable,
			Columns: []string{platform.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   platform.AccountsTable,
			Columns: []string{platform.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.APIKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   platform.APIKeysTable,
			Columns: platform.APIKeysPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAPIKeysIDs(); len(nodes) > 0 && !_u.mutation.APIKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   platform.APIKeysTable,
			Columns: platform.APIKeysPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeysIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   platform.APIKeysTable,
			Columns: platform.APIKeysPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   platform.UsageLogsTable,
			Columns: []string{platform.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsageLogsIDs(); len(nodes) > 0 && !_u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   platform.UsageLogsTable,
			Columns: []string{platform.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsageLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   platform.UsageLogsTable,
			Columns: []string{platform.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{platform.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PlatformUpdateOne is the builder for updating a single Platform entity.
type PlatformUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PlatformMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PlatformUpdateOne) SetUpdatedAt(v time.Time) *PlatformUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCode sets the "code" field.
func (_u *PlatformUpdateOne) SetCode(v string) *PlatformUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *PlatformUpdateOne) SetNillableCode(v *string) *PlatformUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *PlatformUpdateOne) SetName(v string) *PlatformUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PlatformUpdateOne) SetNillableName(v *string) *PlatformUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAccountPlatform sets the "account_platform" field.
func (_u *PlatformUpdateOne) SetAccountPlatform(v string) *PlatformUpdateOne {
	_u.mutation.SetAccountPlatform(v)
	return _u
}

// SetNillableAccountPlatform sets the "account_platform" field if the given value is not nil.
func (_u *PlatformUpdateOne) SetNillableAccountPlatform(v *string) *PlatformUpdateOne {
	if v != nil {
		_u.SetAccountPlatform(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *PlatformUpdateOne) SetStatus(v string) *PlatformUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PlatformUpdateOne) SetNillableStatus(v *string) *PlatformUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetEndpointCapabilities sets the "endpoint_capabilities" field.
func (_u *PlatformUpdateOne) SetEndpointCapabilities(v []string) *PlatformUpdateOne {
	_u.mutation.SetEndpointCapabilities(v)
	return _u
}

// AppendEndpointCapabilities appends value to the "endpoint_capabilities" field.
func (_u *PlatformUpdateOne) AppendEndpointCapabilities(v []string) *PlatformUpdateOne {
	_u.mutation.AppendEndpointCapabilities(v)
	return _u
}

// AddModelRuleIDs adds the "model_rules" edge to the PlatformModelRule entity by IDs.
func (_u *PlatformUpdateOne) AddModelRuleIDs(ids ...int64) *PlatformUpdateOne {
	_u.mutation.AddModelRuleIDs(ids...)
	return _u
}

// AddModelRules adds the "model_rules" edges to the PlatformModelRule entity.
func (_u *PlatformUpdateOne) AddModelRules(v ...*PlatformModelRule) *PlatformUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddModelRuleIDs(ids...)
}

// AddAccountIDs adds the "accounts" edge to the Account entity by IDs.
func (_u *PlatformUpdateOne) AddAccountIDs(ids ...int64) *PlatformUpdateOne {
	_u.mutation.AddAccountIDs(ids...)
	return _u
}

// AddAccounts adds the "accounts" edges to the Account entity.
func (_u *PlatformUpdateOne) AddAccounts(v ...*Account) *PlatformUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAccountIDs(ids...)
}

// AddAPIKeyIDs adds the "api_keys" edge to the APIKey entity by IDs.
func (_u *PlatformUpdateOne) AddAPIKeyIDs(ids ...int64) *PlatformUpdateOne {
	_u.mutation.AddAPIKeyIDs(ids...)
	return _u
}

// AddAPIKeys adds the "api_keys" edges to the APIKey entity.
func (_u *PlatformUpdateOne) AddAPIKeys(v ...*APIKey) *PlatformUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAPIKeyIDs(ids...)
}

// AddUsageLogIDs adds the "usage_logs" edge to the UsageLog entity by IDs.
func (_u *PlatformUpdateOne) AddUsageLogIDs(ids ...int64) *PlatformUpdateOne {
	_u.mutation.AddUsageLogIDs(ids...)
	return _u
}

// AddUsageLogs adds the "usage_logs" edges to the UsageLog entity.
func (_u *PlatformUpdateOne) AddUsageLogs(v ...*UsageLog) *PlatformUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUsageLogIDs(ids...)
}

// Mutation returns the PlatformMutation object of the builder.
func (_u *PlatformUpdateOne) Mutation() *PlatformMutation {
	return _u.mutation
}

// ClearModelRules clears all "model_rules" edges to the PlatformModelRule entity.
func (_u *PlatformUpdateOne) ClearModelRules() *PlatformUpdateOne {
	_u.mutation.ClearModelRules()
	return _u
}

// RemoveModelRuleIDs removes the "model_rules" edge to PlatformModelRule entities by IDs.
func (_u *PlatformUpdateOne) RemoveModelRuleIDs(ids ...int64) *PlatformUpdateOne {
	_u.mutation.RemoveModelRuleIDs(ids...)
	return _u
}

// RemoveModelRules removes "model_rules" edges to PlatformModelRule entities.
func (_u *PlatformUpdateOne) RemoveModelRules(v ...*PlatformModelRule) *PlatformUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveModelRuleIDs(ids...)
}

// ClearAccounts clears all "accounts" edges to the Account entity.
func (_u *PlatformUpdateOne) ClearAccounts() *PlatformUpdateOne {
	_u.mutation.ClearAccounts()
	return _u
}

// RemoveAccountIDs removes the "accounts" edge to Account entities by IDs.
func (_u *PlatformUpdateOne) RemoveAccountIDs(ids ...int64) *PlatformUpdateOne {
	_u.mutation.RemoveAccountIDs(ids...)
	return _u
}

// RemoveAccounts removes "accounts" edges to Account entities.
func (_u *PlatformUpdateOne) RemoveAccounts(v ...*Account) *PlatformUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAccountIDs(ids...)
}

// ClearAPIKeys clears all "api_keys" edges to the APIKey entity.
func (_u *PlatformUpdateOne) ClearAPIKeys() *PlatformUpdateOne {
	_u.mutation.ClearAPIKeys()
	return _u
}

// RemoveAPIKeyIDs removes the "api_keys" edge to APIKey entities by IDs.
func (_u *PlatformUpdateOne) RemoveAPIKeyIDs(ids ...int64) *PlatformUpdateOne {
	_u.mutation.RemoveAPIKeyIDs(ids...)
	return _u
}

// RemoveAPIKeys removes "api_keys" edges to APIKey entities.
func (_u *PlatformUpdateOne) RemoveAPIKeys(v ...*APIKey) *PlatformUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAPIKeyIDs(ids...)
}

// ClearUsageLogs clears all "usage_logs" edges to the UsageLog entity.
func (_u *PlatformUpdateOne) ClearUsageLogs() *PlatformUpdateOne {
	_u.mutation.ClearUsageLogs()
	return _u
}

// RemoveUsageLogIDs removes the "usage_logs" edge to UsageLog entities by IDs.
func (_u *PlatformUpdateOne) RemoveUsageLogIDs(ids ...int64) *PlatformUpdateOne {
	_u.mutation.RemoveUsageLogIDs(ids...)
	return _u
}

// RemoveUsageLogs removes "usage_logs" edges to UsageLog entities.
func (_u *PlatformUpdateOne) RemoveUsageLogs(v ...*UsageLog) *PlatformUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUsageLogIDs(ids...)
}

// Where appends a list predicates to the PlatformUpdate builder.
func (_u *PlatformUpdateOne) Where(ps ...predicate.Platform) *PlatformUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PlatformUpdateOne) Select(field string, fields ...string) *PlatformUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Platform entity.
func (_u *PlatformUpdateOne) Save(ctx context.Context) (*Platform, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PlatformUpdateOne) SaveX(ctx context.Context) *Platform {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PlatformUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PlatformUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PlatformUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := platform.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PlatformUpdateOne) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := platform.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Platform.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := platform.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Platform.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AccountPlatform(); ok {
		if err := platform.AccountPlatformValidator(v); err != nil {
			return &ValidationError{Name: "account_platform", err: fmt.Errorf(`ent: validator failed for field "Platform.account_platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := platform.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Platform.status": %w`, err)}
		}
	}
	return nil
}

func (_u *PlatformUpdateOne) sqlSave(ctx context.Context) (_node *Platform, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(platform.Table, platform.Columns, sqlgraph.NewFieldSpec(platform.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Platform.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, platform.FieldID)
		for _, f := range fields {
			if !platform.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != platform.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(platform.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(platform.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(platform.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountPlatform(); ok {
		_spec.SetField(platform.FieldAccountPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(platform.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.EndpointCapabilities(); ok {
		_spec.SetField(platform.FieldEndpointCapabilities, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedEndpointCapabilities(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, platform.FieldEndpointCapabilities, value)
		})
	}
	if _u.mutation.ModelRulesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   platform.ModelRulesTable,
			Columns: []string{platform.ModelRulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(platformmodelrule.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedModelRulesIDs(); len(nodes) > 0 && !_u.mutation.ModelRulesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   platform.ModelRulesTable,
			Columns: []string{platform.ModelRulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(platformmodelrule.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ModelRulesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   platform.ModelRulesTable,
			Columns: []string{platform.ModelRulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(platformmodelrule.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   platform.AccountsTable,
			Columns: []string{platform.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAccountsIDs(); len(nodes) > 0 && !_u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   platform.AccountsTable,
			Columns: []string{platform.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   platform.AccountsTable,
			Columns: []string{platform.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.APIKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   platform.APIKeysTable,
			Columns: platform.APIKeysPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAPIKeysIDs(); len(nodes) > 0 && !_u.mutation.APIKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   platform.APIKeysTable,
			Columns: platform.APIKeysPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeysIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   platform.APIKeysTable,
			Columns: platform.APIKeysPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   platform.UsageLogsTable,
			Columns: []string{platform.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsageLogsIDs(); len(nodes) > 0 && !_u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   platform.UsageLogsTable,
			Columns: []string{platform.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsageLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   platform.UsageLogsTable,
			Columns: []string{platform.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Platform{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{platform.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
