// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/platform"
	"github.com/Wei-Shaw/sub2api/ent/platformmodelrule"
)

// PlatformModelRule is the model entity for the PlatformModelRule schema.
type PlatformModelRule struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// PlatformID holds the value of the "platform_id" field.
	PlatformID int64 `json:"platform_id,omitempty"`
	// ModelPattern holds the value of the "model_pattern" field.
	ModelPattern string `json:"model_pattern,omitempty"`
	// UpstreamModel holds the value of the "upstream_model" field.
	UpstreamModel string `json:"upstream_model,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PlatformModelRuleQuery when eager-loading is set.
	Edges        PlatformModelRuleEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PlatformModelRuleEdges holds the relations/edges for other nodes in the graph.
type PlatformModelRuleEdges struct {
	// Platform holds the value of the platform edge.
	Platform *Platform `json:"platform,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PlatformOrErr returns the Platform value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PlatformModelRuleEdges) PlatformOrErr() (*Platform, error) {
	if e.Platform != nil {
		return e.Platform, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: platform.Label}
	}
	return nil, &NotLoadedError{edge: "platform"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PlatformModelRule) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case platformmodelrule.FieldID, platformmodelrule.FieldPlatformID:
			values[i] = new(sql.NullInt64)
		case platformmodelrule.FieldModelPattern, platformmodelrule.FieldUpstreamModel, platformmodelrule.FieldStatus:
			values[i] = new(sql.NullString)
		case platformmodelrule.FieldCreatedAt, platformmodelrule.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PlatformModelRule fields.
func (_m *PlatformModelRule) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case platformmodelrule.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case platformmodelrule.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case platformmodelrule.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case platformmodelrule.FieldPlatformID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field platform_id", values[i])
			} else if value.Valid {
				_m.PlatformID = value.Int64
			}
		case platformmodelrule.FieldModelPattern:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model_pattern", values[i])
			} else if value.Valid {
				_m.ModelPattern = value.String
			}
		case platformmodelrule.FieldUpstreamModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_model", values[i])
			} else if value.Valid {
				_m.UpstreamModel = value.String
			}
		case platformmodelrule.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PlatformModelRule.
// This includes values selected through modifiers, order, etc.
func (_m *PlatformModelRule) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPlatform queries the "platform" edge of the PlatformModelRule entity.
func (_m *PlatformModelRule) QueryPlatform() *PlatformQuery {
	return NewPlatformModelRuleClient(_m.config).QueryPlatform(_m)
}

// Update returns a builder for updating this PlatformModelRule.
// Note that you need to call PlatformModelRule.Unwrap() before calling this method if this PlatformModelRule
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PlatformModelRule) Update() *PlatformModelRuleUpdateOne {
	return NewPlatformModelRuleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PlatformModelRule entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PlatformModelRule) Unwrap() *PlatformModelRule {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PlatformModelRule is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PlatformModelRule) String() string {
	var builder strings.Builder
	builder.WriteString("PlatformModelRule(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("platform_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PlatformID))
	builder.WriteString(", ")
	builder.WriteString("model_pattern=")
	builder.WriteString(_m.ModelPattern)
	builder.WriteString(", ")
	builder.WriteString("upstream_model=")
	builder.WriteString(_m.UpstreamModel)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteByte(')')
	return builder.String()
}

// PlatformModelRules is a parsable slice of PlatformModelRule.
type PlatformModelRules []*PlatformModelRule
