// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/platformmodelrule"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// PlatformModelRuleDelete is the builder for deleting a PlatformModelRule entity.
type PlatformModelRuleDelete struct {
	config
	hooks    []Hook
	mutation *PlatformModelRuleMutation
}

// Where appends a list predicates to the PlatformModelRuleDelete builder.
func (_d *PlatformModelRuleDelete) Where(ps ...predicate.PlatformModelRule) *PlatformModelRuleDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *PlatformModelRuleDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PlatformModelRuleDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *PlatformModelRuleDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(platformmodelrule.Table, sqlgraph.NewFieldSpec(platformmodelrule.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// PlatformModelRuleDeleteOne is the builder for deleting a single PlatformModelRule entity.
type PlatformModelRuleDeleteOne struct {
	_d *PlatformModelRuleDelete
}

// Where appends a list predicates to the PlatformModelRuleDelete builder.
func (_d *PlatformModelRuleDeleteOne) Where(ps ...predicate.PlatformModelRule) *PlatformModelRuleDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *PlatformModelRuleDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{platformmodelrule.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PlatformModelRuleDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
