// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/platform"
	"github.com/Wei-Shaw/sub2api/ent/platformmodelrule"
)

// PlatformModelRuleCreate is the builder for creating a PlatformModelRule entity.
type PlatformModelRuleCreate struct {
	config
	mutation *PlatformModelRuleMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *PlatformModelRuleCreate) SetCreatedAt(v time.Time) *PlatformModelRuleCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PlatformModelRuleCreate) SetNillableCreatedAt(v *time.Time) *PlatformModelRuleCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PlatformModelRuleCreate) SetUpdatedAt(v time.Time) *PlatformModelRuleCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PlatformModelRuleCreate) SetNillableUpdatedAt(v *time.Time) *PlatformModelRuleCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetPlatformID sets the "platform_id" field.
func (_c *PlatformModelRuleCreate) SetPlatformID(v int64) *PlatformModelRuleCreate {
	_c.mutation.SetPlatformID(v)
	return _c
}

// SetModelPattern sets the "model_pattern" field.
func (_c *PlatformModelRuleCreate) SetModelPattern(v string) *PlatformModelRuleCreate {
	_c.mutation.SetModelPattern(v)
	return _c
}

// SetUpstreamModel sets the "upstream_model" field.
func (_c *PlatformModelRuleCreate) SetUpstreamModel(v string) *PlatformModelRuleCreate {
	_c.mutation.SetUpstreamModel(v)
	return _c
}

// SetNillableUpstreamModel sets the "upstream_model" field if the given value is not nil.
func (_c *PlatformModelRuleCreate) SetNillableUpstreamModel(v *string) *PlatformModelRuleCreate {
	if v != nil {
		_c.SetUpstreamModel(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *PlatformModelRuleCreate) SetStatus(v string) *PlatformModelRuleCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *PlatformModelRuleCreate) SetNillableStatus(v *string) *PlatformModelRuleCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetPlatform sets the "platform" edge to the Platform entity.
func (_c *PlatformModelRuleCreate) SetPlatform(v *Platform) *PlatformModelRuleCreate {
	return _c.SetPlatformID(v.ID)
}

// Mutation returns the PlatformModelRuleMutation object of the builder.
func (_c *PlatformModelRuleCreate) Mutation() *PlatformModelRuleMutation {
	return _c.mutation
}

// Save creates the PlatformModelRule in the database.
func (_c *PlatformModelRuleCreate) Save(ctx context.Context) (*PlatformModelRule, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PlatformModelRuleCreate) SaveX(ctx context.Context) *PlatformModelRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PlatformModelRuleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PlatformModelRuleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PlatformModelRuleCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := platformmodelrule.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := platformmodelrule.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.UpstreamModel(); !ok {
		v := platformmodelrule.DefaultUpstreamModel
		_c.mutation.SetUpstreamModel(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := platformmodelrule.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PlatformModelRuleCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PlatformModelRule.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PlatformModelRule.updated_at"`)}
	}
	if _, ok := _c.mutation.PlatformID(); !ok {
		return &ValidationError{Name: "platform_id", err: errors.New(`ent: missing required field "PlatformModelRule.platform_id"`)}
	}
	if _, ok := _c.mutation.ModelPattern(); !ok {
		return &ValidationError{Name: "model_pattern", err: errors.New(`ent: missing required field "PlatformModelRule.model_pattern"`)}
	}
	if v, ok := _c.mutation.ModelPattern(); ok {
		if err := platformmodelrule.ModelPatternValidator(v); err != nil {
			return &ValidationError{Name: "model_pattern", err: fmt.Errorf(`ent: validator failed for field "PlatformModelRule.model_pattern": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UpstreamModel(); !ok {
		return &ValidationError{Name: "upstream_model", err: errors.New(`ent: missing required field "PlatformModelRule.upstream_model"`)}
	}
	if v, ok := _c.mutation.UpstreamModel(); ok {
		if err := platformmodelrule.UpstreamModelValidator(v); err != nil {
			return &ValidationError{Name: "upstream_model", err: fmt.Errorf(`ent: validator failed for field "PlatformModelRule.upstream_model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "PlatformModelRule.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := platformmodelrule.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PlatformModelRule.status": %w`, err)}
		}
	}
	if len(_c.mutation.PlatformIDs()) == 0 {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required edge "PlatformModelRule.platform"`)}
	}
	return nil
}

func (_c *PlatformModelRuleCreate) sqlSave(ctx context.Context) (*PlatformModelRule, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PlatformModelRuleCreate) createSpec() (*PlatformModelRule, *sqlgraph.CreateSpec) {
	var (
		_node = &PlatformModelRule{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(platformmodelrule.Table, sqlgraph.NewFieldSpec(platformmodelrule.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(platformmodelrule.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(platformmodelrule.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ModelPattern(); ok {
		_spec.SetField(platformmodelrule.FieldModelPattern, field.TypeString, value)
		_node.ModelPattern = value
	}
	if value, ok := _c.mutation.UpstreamModel(); ok {
		_spec.SetField(platformmodelrule.FieldUpstreamModel, field.TypeString, value)
		_node.UpstreamModel = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(platformmodelrule.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if nodes := _c.mutation.PlatformIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   platformmodelrule.PlatformTable,
			Columns: []string{platformmodelrule.PlatformColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(platform.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PlatformID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PlatformModelRule.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PlatformModelRuleUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PlatformModelRuleCreate) OnConflict(opts ...sql.ConflictOption) *PlatformModelRuleUpsertOne {
	_c.conflict = opts
	return &PlatformModelRuleUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PlatformModelRule.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PlatformModelRuleCreate) OnConflictColumns(columns ...string) *PlatformModelRuleUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PlatformModelRuleUpsertOne{
		create: _c,
	}
}

type (
	// PlatformModelRuleUpsertOne is the builder for "upsert"-ing
	//  one PlatformModelRule node.
	PlatformModelRuleUpsertOne struct {
		create *PlatformModelRuleCreate
	}

	// PlatformModelRuleUpsert is the "OnConflict" setter.
	PlatformModelRuleUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *PlatformModelRuleUpsert) SetUpdatedAt(v time.Time) *PlatformModelRuleUpsert {
	u.Set(platformmodelrule.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PlatformModelRuleUpsert) UpdateUpdatedAt() *PlatformModelRuleUpsert {
	u.SetExcluded(platformmodelrule.FieldUpdatedAt)
	return u
}

// SetPlatformID sets the "platform_id" field.
func (u *PlatformModelRuleUpsert) SetPlatformID(v int64) *PlatformModelRuleUpsert {
	u.Set(platformmodelrule.FieldPlatformID, v)
	return u
}

// UpdatePlatformID sets the "platform_id" field to the value that was provided on create.
func (u *PlatformModelRuleUpsert) UpdatePlatformID() *PlatformModelRuleUpsert {
	u.SetExcluded(platformmodelrule.FieldPlatformID)
	return u
}

// SetModelPattern sets the "model_pattern" field.
func (u *PlatformModelRuleUpsert) SetModelPattern(v string) *PlatformModelRuleUpsert {
	u.Set(platformmodelrule.FieldModelPattern, v)
	return u
}

// UpdateModelPattern sets the "model_pattern" field to the value that was provided on create.
func (u *PlatformModelRuleUpsert) UpdateModelPattern() *PlatformModelRuleUpsert {
	u.SetExcluded(platformmodelrule.FieldModelPattern)
	return u
}

// SetUpstreamModel sets the "upstream_model" field.
func (u *PlatformModelRuleUpsert) SetUpstreamModel(v string) *PlatformModelRuleUpsert {
	u.Set(platformmodelrule.FieldUpstreamModel, v)
	return u
}

// UpdateUpstreamModel sets the "upstream_model" field to the value that was provided on create.
func (u *PlatformModelRuleUpsert) UpdateUpstreamModel() *PlatformModelRuleUpsert {
	u.SetExcluded(platformmodelrule.FieldUpstreamModel)
	return u
}

// SetStatus sets the "status" field.
func (u *PlatformModelRuleUpsert) SetStatus(v string) *PlatformModelRuleUpsert {
	u.Set(platformmodelrule.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PlatformModelRuleUpsert) UpdateStatus() *PlatformModelRuleUpsert {
	u.SetExcluded(platformmodelrule.FieldStatus)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.PlatformModelRule.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PlatformModelRuleUpsertOne) UpdateNewValues() *PlatformModelRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(platformmodelrule.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PlatformModelRule.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PlatformModelRuleUpsertOne) Ignore() *PlatformModelRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PlatformModelRuleUpsertOne) DoNothing() *PlatformModelRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PlatformModelRuleCreate.OnConflict
// documentation for more info.
func (u *PlatformModelRuleUpsertOne) Update(set func(*PlatformModelRuleUpsert)) *PlatformModelRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PlatformModelRuleUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PlatformModelRuleUpsertOne) SetUpdatedAt(v time.Time) *PlatformModelRuleUpsertOne {
	return u.Update(func(s *PlatformModelRuleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PlatformModelRuleUpsertOne) UpdateUpdatedAt() *PlatformModelRuleUpsertOne {
	return u.Update(func(s *PlatformModelRuleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetPlatformID sets the "platform_id" field.
func (u *PlatformModelRuleUpsertOne) SetPlatformID(v int64) *PlatformModelRuleUpsertOne {
	return u.Update(func(s *PlatformModelRuleUpsert) {
		s.SetPlatformID(v)
	})
}

// UpdatePlatformID sets the "platform_id" field to the value that was provided on create.
func (u *PlatformModelRuleUpsertOne) UpdatePlatformID() *PlatformModelRuleUpsertOne {
	return u.Update(func(s *PlatformModelRuleUpsert) {
		s.UpdatePlatformID()
	})
}

// SetModelPattern sets the "model_pattern" field.
func (u *PlatformModelRuleUpsertOne) SetModelPattern(v string) *PlatformModelRuleUpsertOne {
	return u.Update(func(s *PlatformModelRuleUpsert) {
		s.SetModelPattern(v)
	})
}

// UpdateModelPattern sets the "model_pattern" field to the value that was provided on create.
func (u *PlatformModelRuleUpsertOne) UpdateModelPattern() *PlatformModelRuleUpsertOne {
	return u.Update(func(s *PlatformModelRuleUpsert) {
		s.UpdateModelPattern()
	})
}

// SetUpstreamModel sets the "upstream_model" field.
func (u *PlatformModelRuleUpsertOne) SetUpstreamModel(v string) *PlatformModelRuleUpsertOne {
	return u.Update(func(s *PlatformModelRuleUpsert) {
		s.SetUpstreamModel(v)
	})
}

// UpdateUpstreamModel sets the "upstream_model" field to the value that was provided on create.
func (u *PlatformModelRuleUpsertOne) UpdateUpstreamModel() *PlatformModelRuleUpsertOne {
	return u.Update(func(s *PlatformModelRuleUpsert) {
		s.UpdateUpstreamModel()
	})
}

// SetStatus sets the "status" field.
func (u *PlatformModelRuleUpsertOne) SetStatus(v string) *PlatformModelRuleUpsertOne {
	return u.Update(func(s *PlatformModelRuleUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PlatformModelRuleUpsertOne) UpdateStatus() *PlatformModelRuleUpsertOne {
	return u.Update(func(s *PlatformModelRuleUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *PlatformModelRuleUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PlatformModelRuleCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PlatformModelRuleUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PlatformModelRuleUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PlatformModelRuleUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PlatformModelRuleCreateBulk is the builder for creating many PlatformModelRule entities in bulk.
type PlatformModelRuleCreateBulk struct {
	config
	err      error
	builders []*PlatformModelRuleCreate
	conflict []sql.ConflictOption
}

// Save creates the PlatformModelRule entities in the database.
func (_c *PlatformModelRuleCreateBulk) Save(ctx context.Context) ([]*PlatformModelRule, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PlatformModelRule, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PlatformModelRuleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PlatformModelRuleCreateBulk) SaveX(ctx context.Context) []*PlatformModelRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PlatformModelRuleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PlatformModelRuleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PlatformModelRule.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PlatformModelRuleUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PlatformModelRuleCreateBulk) OnConflict(opts ...sql.ConflictOption) *PlatformModelRuleUpsertBulk {
	_c.conflict = opts
	return &PlatformModelRuleUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PlatformModelRule.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PlatformModelRuleCreateBulk) OnConflictColumns(columns ...string) *PlatformModelRuleUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PlatformModelRuleUpsertBulk{
		create: _c,
	}
}

// PlatformModelRuleUpsertBulk is the builder for "upsert"-ing
// a bulk of PlatformModelRule nodes.
type PlatformModelRuleUpsertBulk struct {
	create *PlatformModelRuleCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PlatformModelRule.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PlatformModelRuleUpsertBulk) UpdateNewValues() *PlatformModelRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(platformmodelrule.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PlatformModelRule.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PlatformModelRuleUpsertBulk) Ignore() *PlatformModelRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PlatformModelRuleUpsertBulk) DoNothing() *PlatformModelRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PlatformModelRuleCreateBulk.OnConflict
// documentation for more info.
func (u *PlatformModelRuleUpsertBulk) Update(set func(*PlatformModelRuleUpsert)) *PlatformModelRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PlatformModelRuleUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PlatformModelRuleUpsertBulk) SetUpdatedAt(v time.Time) *PlatformModelRuleUpsertBulk {
	return u.Update(func(s *PlatformModelRuleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PlatformModelRuleUpsertBulk) UpdateUpdatedAt() *PlatformModelRuleUpsertBulk {
	return u.Update(func(s *PlatformModelRuleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetPlatformID sets the "platform_id" field.
func (u *PlatformModelRuleUpsertBulk) SetPlatformID(v int64) *PlatformModelRuleUpsertBulk {
	return u.Update(func(s *PlatformModelRuleUpsert) {
		s.SetPlatformID(v)
	})
}

// UpdatePlatformID sets the "platform_id" field to the value that was provided on create.
func (u *PlatformModelRuleUpsertBulk) UpdatePlatformID() *PlatformModelRuleUpsertBulk {
	return u.Update(func(s *PlatformModelRuleUpsert) {
		s.UpdatePlatformID()
	})
}

// SetModelPattern sets the "model_pattern" field.
func (u *PlatformModelRuleUpsertBulk) SetModelPattern(v string) *PlatformModelRuleUpsertBulk {
	return u.Update(func(s *PlatformModelRuleUpsert) {
		s.SetModelPattern(v)
	})
}

// UpdateModelPattern sets the "model_pattern" field to the value that was provided on create.
func (u *PlatformModelRuleUpsertBulk) UpdateModelPattern() *PlatformModelRuleUpsertBulk {
	return u.Update(func(s *PlatformModelRuleUpsert) {
		s.UpdateModelPattern()
	})
}

// SetUpstreamModel sets the "upstream_model" field.
func (u *PlatformModelRuleUpsertBulk) SetUpstreamModel(v string) *PlatformModelRuleUpsertBulk {
	return u.Update(func(s *PlatformModelRuleUpsert) {
		s.SetUpstreamModel(v)
	})
}

// UpdateUpstreamModel sets the "upstream_model" field to the value that was provided on create.
func (u *PlatformModelRuleUpsertBulk) UpdateUpstreamModel() *PlatformModelRuleUpsertBulk {
	return u.Update(func(s *PlatformModelRuleUpsert) {
		s.UpdateUpstreamModel()
	})
}

// SetStatus sets the "status" field.
func (u *PlatformModelRuleUpsertBulk) SetStatus(v string) *PlatformModelRuleUpsertBulk {
	return u.Update(func(s *PlatformModelRuleUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PlatformModelRuleUpsertBulk) UpdateStatus() *PlatformModelRuleUpsertBulk {
	return u.Update(func(s *PlatformModelRuleUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *PlatformModelRuleUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PlatformModelRuleCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PlatformModelRuleCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PlatformModelRuleUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
