// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/platform"
	"github.com/Wei-Shaw/sub2api/ent/platformmodelrule"
	"github.com/Wei-Shaw/sub2api/ent/usagelog"
)

// PlatformCreate is the builder for creating a Platform entity.
type PlatformCreate struct {
	config
	mutation *PlatformMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *PlatformCreate) SetCreatedAt(v time.Time) *PlatformCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PlatformCreate) SetNillableCreatedAt(v *time.Time) *PlatformCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PlatformCreate) SetUpdatedAt(v time.Time) *PlatformCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PlatformCreate) SetNillableUpdatedAt(v *time.Time) *PlatformCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCode sets the "code" field.
func (_c *PlatformCreate) SetCode(v string) *PlatformCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetName sets the "name" field.
func (_c *PlatformCreate) SetName(v string) *PlatformCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetAccountPlatform sets the "account_platform" field.
func (_c *PlatformCreate) SetAccountPlatform(v string) *PlatformCreate {
	_c.mutation.SetAccountPlatform(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *PlatformCreate) SetStatus(v string) *PlatformCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *PlatformCreate) SetNillableStatus(v *string) *PlatformCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetEndpointCapabilities sets the "endpoint_capabilities" field.
func (_c *PlatformCreate) SetEndpointCapabilities(v []string) *PlatformCreate {
	_c.mutation.SetEndpointCapabilities(v)
	return _c
}

// AddModelRuleIDs adds the "model_rules" edge to the PlatformModelRule entity by IDs.
func (_c *PlatformCreate) AddModelRuleIDs(ids ...int64) *PlatformCreate {
	_c.mutation.AddModelRuleIDs(ids...)
	return _c
}

// AddModelRules adds the "model_rules" edges to the PlatformModelRule entity.
func (_c *PlatformCreate) AddModelRules(v ...*PlatformModelRule) *PlatformCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddModelRuleIDs(ids...)
}

// AddAccountIDs adds the "accounts" edge to the Account entity by IDs.
func (_c *PlatformCreate) AddAccountIDs(ids ...int64) *PlatformCreate {
	_c.mutation.AddAccountIDs(ids...)
	return _c
}

// AddAccounts adds the "accounts" edges to the Account entity.
func (_c *PlatformCreate) AddAccounts(v ...*Account) *PlatformCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAccountIDs(ids...)
}

// AddAPIKeyIDs adds the "api_keys" edge to the APIKey entity by IDs.
func (_c *PlatformCreate) AddAPIKeyIDs(ids ...int64) *PlatformCreate {
	_c.mutation.AddAPIKeyIDs(ids...)
	return _c
}

// AddAPIKeys adds the "api_keys" edges to the APIKey entity.
func (_c *PlatformCreate) AddAPIKeys(v ...*APIKey) *PlatformCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAPIKeyIDs(ids...)
}

// AddUsageLogIDs adds the "usage_logs" edge to the UsageLog entity by IDs.
func (_c *PlatformCreate) AddUsageLogIDs(ids ...int64) *PlatformCreate {
	_c.mutation.AddUsageLogIDs(ids...)
	return _c
}

// AddUsageLogs adds the "usage_logs" edges to the UsageLog entity.
func (_c *PlatformCreate) AddUsageLogs(v ...*UsageLog) *PlatformCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddUsageLogIDs(ids...)
}

// Mutation returns the PlatformMutation object of the builder.
func (_c *PlatformCreate) Mutation() *PlatformMutation {
	return _c.mutation
}

// Save creates the Platform in the database.
func (_c *PlatformCreate) Save(ctx context.Context) (*Platform, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PlatformCreate) SaveX(ctx context.Context) *Platform {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PlatformCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PlatformCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PlatformCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := platform.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := platform.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := platform.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.EndpointCapabilities(); !ok {
		v := platform.DefaultEndpointCapabilities
		_c.mutation.SetEndpointCapabilities(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PlatformCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Platform.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Platform.updated_at"`)}
	}
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "Platform.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := platform.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Platform.code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Platform.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := platform.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Platform.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AccountPlatform(); !ok {
		return &ValidationError{Name: "account_platform", err: errors.New(`ent: missing required field "Platform.account_platform"`)}
	}
	if v, ok := _c.mutation.AccountPlatform(); ok {
		if err := platform.AccountPlatformValidator(v); err != nil {
			return &ValidationError{Name: "account_platform", err: fmt.Errorf(`ent: validator failed for field "Platform.account_platform": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Platform.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := platform.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Platform.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EndpointCapabilities(); !ok {
		return &ValidationError{Name: "endpoint_capabilities", err: errors.New(`ent: missing required field "Platform.endpoint_capabilities"`)}
	}
	return nil
}

func (_c *PlatformCreate) sqlSave(ctx context.Context) (*Platform, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PlatformCreate) createSpec() (*Platform, *sqlgraph.CreateSpec) {
	var (
		_node = &Platform{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(platform.Table, sqlgraph.NewFieldSpec(platform.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(platform.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(platform.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(platform.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(platform.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.AccountPlatform(); ok {
		_spec.SetField(platform.FieldAccountPlatform, field.TypeString, value)
		_node.AccountPlatform = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(platform.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.EndpointCapabilities(); ok {
		_spec.SetField(platform.FieldEndpointCapabilities, field.TypeJSON, value)
		_node.EndpointCapabilities = value
	}
	if nodes := _c.mutation.ModelRulesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   platform.ModelRulesTable,
			Columns: []string{platform.ModelRulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(platformmodelrule.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   platform.AccountsTable,
			Columns: []string{platform.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.APIKeysIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   platform.APIKeysTable,
			Columns: platform.APIKeysPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UsageLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   platform.UsageLogsTable,
			Columns: []string{platform.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Platform.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PlatformUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PlatformCreate) OnConflict(opts ...sql.ConflictOption) *PlatformUpsertOne {
	_c.conflict = opts
	return &PlatformUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Platform.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PlatformCreate) OnConflictColumns(columns ...string) *PlatformUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PlatformUpsertOne{
		create: _c,
	}
}

type (
	// PlatformUpsertOne is the builder for "upsert"-ing
	//  one Platform node.
	PlatformUpsertOne struct {
		create *PlatformCreate
	}

	// PlatformUpsert is the "OnConflict" setter.
	PlatformUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *PlatformUpsert) SetUpdatedAt(v time.Time) *PlatformUpsert {
	u.Set(platform.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PlatformUpsert) UpdateUpdatedAt() *PlatformUpsert {
	u.SetExcluded(platform.FieldUpdatedAt)
	return u
}

// SetCode sets the "code" field.
func (u *PlatformUpsert) SetCode(v string) *PlatformUpsert {
	u.Set(platform.FieldCode, v)
	return u
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *PlatformUpsert) UpdateCode() *PlatformUpsert {
	u.SetExcluded(platform.FieldCode)
	return u
}

// SetName sets the "name" field.
func (u *PlatformUpsert) SetName(v string) *PlatformUpsert {
	u.Set(platform.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *PlatformUpsert) UpdateName() *PlatformUpsert {
	u.SetExcluded(platform.FieldName)
	return u
}

// SetAccountPlatform sets the "account_platform" field.
func (u *PlatformUpsert) SetAccountPlatform(v string) *PlatformUpsert {
	u.Set(platform.FieldAccountPlatform, v)
	return u
}

// UpdateAccountPlatform sets the "account_platform" field to the value that was provided on create.
func (u *PlatformUpsert) UpdateAccountPlatform() *PlatformUpsert {
	u.SetExcluded(platform.FieldAccountPlatform)
	return u
}

// SetStatus sets the "status" field.
func (u *PlatformUpsert) SetStatus(v string) *PlatformUpsert {
	u.Set(platform.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PlatformUpsert) UpdateStatus() *PlatformUpsert {
	u.SetExcluded(platform.FieldStatus)
	return u
}

// SetEndpointCapabilities sets the "endpoint_capabilities" field.
func (u *PlatformUpsert) SetEndpointCapabilities(v []string) *PlatformUpsert {
	u.Set(platform.FieldEndpointCapabilities, v)
	return u
}

// UpdateEndpointCapabilities sets the "endpoint_capabilities" field to the value that was provided on create.
func (u *PlatformUpsert) UpdateEndpointCapabilities() *PlatformUpsert {
	u.SetExcluded(platform.FieldEndpointCapabilities)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Platform.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PlatformUpsertOne) UpdateNewValues() *PlatformUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(platform.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Platform.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PlatformUpsertOne) Ignore() *PlatformUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PlatformUpsertOne) DoNothing() *PlatformUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PlatformCreate.OnConflict
// documentation for more info.
func (u *PlatformUpsertOne) Update(set func(*PlatformUpsert)) *PlatformUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PlatformUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PlatformUpsertOne) SetUpdatedAt(v time.Time) *PlatformUpsertOne {
	return u.Update(func(s *PlatformUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PlatformUpsertOne) UpdateUpdatedAt() *PlatformUpsertOne {
	return u.Update(func(s *PlatformUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetCode sets the "code" field.
func (u *PlatformUpsertOne) SetCode(v string) *PlatformUpsertOne {
	return u.Update(func(s *PlatformUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *PlatformUpsertOne) UpdateCode() *PlatformUpsertOne {
	return u.Update(func(s *PlatformUpsert) {
		s.UpdateCode()
	})
}

// SetName sets the "name" field.
func (u *PlatformUpsertOne) SetName(v string) *PlatformUpsertOne {
	return u.Update(func(s *PlatformUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *PlatformUpsertOne) UpdateName() *PlatformUpsertOne {
	return u.Update(func(s *PlatformUpsert) {
		s.UpdateName()
	})
}

// SetAccountPlatform sets the "account_platform" field.
func (u *PlatformUpsertOne) SetAccountPlatform(v string) *PlatformUpsertOne {
	return u.Update(func(s *PlatformUpsert) {
		s.SetAccountPlatform(v)
	})
}

// UpdateAccountPlatform sets the "account_platform" field to the value that was provided on create.
func (u *PlatformUpsertOne) UpdateAccountPlatform() *PlatformUpsertOne {
	return u.Update(func(s *PlatformUpsert) {
		s.UpdateAccountPlatform()
	})
}

// SetStatus sets the "status" field.
func (u *PlatformUpsertOne) SetStatus(v string) *PlatformUpsertOne {
	return u.Update(func(s *PlatformUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PlatformUpsertOne) UpdateStatus() *PlatformUpsertOne {
	return u.Update(func(s *PlatformUpsert) {
		s.UpdateStatus()
	})
}

// SetEndpointCapabilities sets the "endpoint_capabilities" field.
func (u *PlatformUpsertOne) SetEndpointCapabilities(v []string) *PlatformUpsertOne {
	return u.Update(func(s *PlatformUpsert) {
		s.SetEndpointCapabilities(v)
	})
}

// UpdateEndpointCapabilities sets the "endpoint_capabilities" field to the value that was provided on create.
func (u *PlatformUpsertOne) UpdateEndpointCapabilities() *PlatformUpsertOne {
	return u.Update(func(s *PlatformUpsert) {
		s.UpdateEndpointCapabilities()
	})
}

// Exec executes the query.
func (u *PlatformUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PlatformCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PlatformUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PlatformUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PlatformUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PlatformCreateBulk is the builder for creating many Platform entities in bulk.
type PlatformCreateBulk struct {
	config
	err      error
	builders []*PlatformCreate
	conflict []sql.ConflictOption
}

// Save creates the Platform entities in the database.
func (_c *PlatformCreateBulk) Save(ctx context.Context) ([]*Platform, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Platform, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PlatformMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PlatformCreateBulk) SaveX(ctx context.Context) []*Platform {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PlatformCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PlatformCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Platform.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PlatformUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PlatformCreateBulk) OnConflict(opts ...sql.ConflictOption) *PlatformUpsertBulk {
	_c.conflict = opts
	return &PlatformUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Platform.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PlatformCreateBulk) OnConflictColumns(columns ...string) *PlatformUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PlatformUpsertBulk{
		create: _c,
	}
}

// PlatformUpsertBulk is the builder for "upsert"-ing
// a bulk of Platform nodes.
type PlatformUpsertBulk struct {
	create *PlatformCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Platform.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PlatformUpsertBulk) UpdateNewValues() *PlatformUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(platform.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Platform.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PlatformUpsertBulk) Ignore() *PlatformUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PlatformUpsertBulk) DoNothing() *PlatformUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PlatformCreateBulk.OnConflict
// documentation for more info.
func (u *PlatformUpsertBulk) Update(set func(*PlatformUpsert)) *PlatformUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PlatformUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PlatformUpsertBulk) SetUpdatedAt(v time.Time) *PlatformUpsertBulk {
	return u.Update(func(s *PlatformUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PlatformUpsertBulk) UpdateUpdatedAt() *PlatformUpsertBulk {
	return u.Update(func(s *PlatformUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetCode sets the "code" field.
func (u *PlatformUpsertBulk) SetCode(v string) *PlatformUpsertBulk {
	return u.Update(func(s *PlatformUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *PlatformUpsertBulk) UpdateCode() *PlatformUpsertBulk {
	return u.Update(func(s *PlatformUpsert) {
		s.UpdateCode()
	})
}

// SetName sets the "name" field.
func (u *PlatformUpsertBulk) SetName(v string) *PlatformUpsertBulk {
	return u.Update(func(s *PlatformUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *PlatformUpsertBulk) UpdateName() *PlatformUpsertBulk {
	return u.Update(func(s *PlatformUpsert) {
		s.UpdateName()
	})
}

// SetAccountPlatform sets the "account_platform" field.
func (u *PlatformUpsertBulk) SetAccountPlatform(v string) *PlatformUpsertBulk {
	return u.Update(func(s *PlatformUpsert) {
		s.SetAccountPlatform(v)
	})
}

// UpdateAccountPlatform sets the "account_platform" field to the value that was provided on create.
func (u *PlatformUpsertBulk) UpdateAccountPlatform() *PlatformUpsertBulk {
	return u.Update(func(s *PlatformUpsert) {
		s.UpdateAccountPlatform()
	})
}

// SetStatus sets the "status" field.
func (u *PlatformUpsertBulk) SetStatus(v string) *PlatformUpsertBulk {
	return u.Update(func(s *PlatformUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PlatformUpsertBulk) UpdateStatus() *PlatformUpsertBulk {
	return u.Update(func(s *PlatformUpsert) {
		s.UpdateStatus()
	})
}

// SetEndpointCapabilities sets the "endpoint_capabilities" field.
func (u *PlatformUpsertBulk) SetEndpointCapabilities(v []string) *PlatformUpsertBulk {
	return u.Update(func(s *PlatformUpsert) {
		s.SetEndpointCapabilities(v)
	})
}

// UpdateEndpointCapabilities sets the "endpoint_capabilities" field to the value that was provided on create.
func (u *PlatformUpsertBulk) UpdateEndpointCapabilities() *PlatformUpsertBulk {
	return u.Update(func(s *PlatformUpsert) {
		s.UpdateEndpointCapabilities()
	})
}

// Exec executes the query.
func (u *PlatformUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PlatformCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PlatformCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PlatformUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
