// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/redeemcode"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionplan"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// RedeemCodeUpdate is the builder for updating RedeemCode entities.
type RedeemCodeUpdate struct {
	config
	hooks    []Hook
	mutation *RedeemCodeMutation
}

// Where appends a list predicates to the RedeemCodeUpdate builder.
func (_u *RedeemCodeUpdate) Where(ps ...predicate.RedeemCode) *RedeemCodeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCode sets the "code" field.
func (_u *RedeemCodeUpdate) SetCode(v string) *RedeemCodeUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *RedeemCodeUpdate) SetNillableCode(v *string) *RedeemCodeUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *RedeemCodeUpdate) SetType(v string) *RedeemCodeUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *RedeemCodeUpdate) SetNillableType(v *string) *RedeemCodeUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *RedeemCodeUpdate) SetValue(v float64) *RedeemCodeUpdate {
	_u.mutation.ResetValue()
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *RedeemCodeUpdate) SetNillableValue(v *float64) *RedeemCodeUpdate {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// AddValue adds value to the "value" field.
func (_u *RedeemCodeUpdate) AddValue(v float64) *RedeemCodeUpdate {
	_u.mutation.AddValue(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *RedeemCodeUpdate) SetStatus(v string) *RedeemCodeUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RedeemCodeUpdate) SetNillableStatus(v *string) *RedeemCodeUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUsedBy sets the "used_by" field.
func (_u *RedeemCodeUpdate) SetUsedBy(v int64) *RedeemCodeUpdate {
	_u.mutation.SetUsedBy(v)
	return _u
}

// SetNillableUsedBy sets the "used_by" field if the given value is not nil.
func (_u *RedeemCodeUpdate) SetNillableUsedBy(v *int64) *RedeemCodeUpdate {
	if v != nil {
		_u.SetUsedBy(*v)
	}
	return _u
}

// ClearUsedBy clears the value of the "used_by" field.
func (_u *RedeemCodeUpdate) ClearUsedBy() *RedeemCodeUpdate {
	_u.mutation.ClearUsedBy()
	return _u
}

// SetUsedAt sets the "used_at" field.
func (_u *RedeemCodeUpdate) SetUsedAt(v time.Time) *RedeemCodeUpdate {
	_u.mutation.SetUsedAt(v)
	return _u
}

// SetNillableUsedAt sets the "used_at" field if the given value is not nil.
func (_u *RedeemCodeUpdate) SetNillableUsedAt(v *time.Time) *RedeemCodeUpdate {
	if v != nil {
		_u.SetUsedAt(*v)
	}
	return _u
}

// ClearUsedAt clears the value of the "used_at" field.
func (_u *RedeemCodeUpdate) ClearUsedAt() *RedeemCodeUpdate {
	_u.mutation.ClearUsedAt()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *RedeemCodeUpdate) SetNotes(v string) *RedeemCodeUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *RedeemCodeUpdate) SetNillableNotes(v *string) *RedeemCodeUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *RedeemCodeUpdate) ClearNotes() *RedeemCodeUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *RedeemCodeUpdate) SetExpiresAt(v time.Time) *RedeemCodeUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *RedeemCodeUpdate) SetNillableExpiresAt(v *time.Time) *RedeemCodeUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *RedeemCodeUpdate) ClearExpiresAt() *RedeemCodeUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetSubscriptionPlanID sets the "subscription_plan_id" field.
func (_u *RedeemCodeUpdate) SetSubscriptionPlanID(v int64) *RedeemCodeUpdate {
	_u.mutation.SetSubscriptionPlanID(v)
	return _u
}

// SetNillableSubscriptionPlanID sets the "subscription_plan_id" field if the given value is not nil.
func (_u *RedeemCodeUpdate) SetNillableSubscriptionPlanID(v *int64) *RedeemCodeUpdate {
	if v != nil {
		_u.SetSubscriptionPlanID(*v)
	}
	return _u
}

// ClearSubscriptionPlanID clears the value of the "subscription_plan_id" field.
func (_u *RedeemCodeUpdate) ClearSubscriptionPlanID() *RedeemCodeUpdate {
	_u.mutation.ClearSubscriptionPlanID()
	return _u
}

// SetPlanNameSnapshot sets the "plan_name_snapshot" field.
func (_u *RedeemCodeUpdate) SetPlanNameSnapshot(v string) *RedeemCodeUpdate {
	_u.mutation.SetPlanNameSnapshot(v)
	return _u
}

// SetNillablePlanNameSnapshot sets the "plan_name_snapshot" field if the given value is not nil.
func (_u *RedeemCodeUpdate) SetNillablePlanNameSnapshot(v *string) *RedeemCodeUpdate {
	if v != nil {
		_u.SetPlanNameSnapshot(*v)
	}
	return _u
}

// SetDailyLimitUsdSnapshot sets the "daily_limit_usd_snapshot" field.
func (_u *RedeemCodeUpdate) SetDailyLimitUsdSnapshot(v float64) *RedeemCodeUpdate {
	_u.mutation.ResetDailyLimitUsdSnapshot()
	_u.mutation.SetDailyLimitUsdSnapshot(v)
	return _u
}

// SetNillableDailyLimitUsdSnapshot sets the "daily_limit_usd_snapshot" field if the given value is not nil.
func (_u *RedeemCodeUpdate) SetNillableDailyLimitUsdSnapshot(v *float64) *RedeemCodeUpdate {
	if v != nil {
		_u.SetDailyLimitUsdSnapshot(*v)
	}
	return _u
}

// AddDailyLimitUsdSnapshot adds value to the "daily_limit_usd_snapshot" field.
func (_u *RedeemCodeUpdate) AddDailyLimitUsdSnapshot(v float64) *RedeemCodeUpdate {
	_u.mutation.AddDailyLimitUsdSnapshot(v)
	return _u
}

// ClearDailyLimitUsdSnapshot clears the value of the "daily_limit_usd_snapshot" field.
func (_u *RedeemCodeUpdate) ClearDailyLimitUsdSnapshot() *RedeemCodeUpdate {
	_u.mutation.ClearDailyLimitUsdSnapshot()
	return _u
}

// SetWeeklyLimitUsdSnapshot sets the "weekly_limit_usd_snapshot" field.
func (_u *RedeemCodeUpdate) SetWeeklyLimitUsdSnapshot(v float64) *RedeemCodeUpdate {
	_u.mutation.ResetWeeklyLimitUsdSnapshot()
	_u.mutation.SetWeeklyLimitUsdSnapshot(v)
	return _u
}

// SetNillableWeeklyLimitUsdSnapshot sets the "weekly_limit_usd_snapshot" field if the given value is not nil.
func (_u *RedeemCodeUpdate) SetNillableWeeklyLimitUsdSnapshot(v *float64) *RedeemCodeUpdate {
	if v != nil {
		_u.SetWeeklyLimitUsdSnapshot(*v)
	}
	return _u
}

// AddWeeklyLimitUsdSnapshot adds value to the "weekly_limit_usd_snapshot" field.
func (_u *RedeemCodeUpdate) AddWeeklyLimitUsdSnapshot(v float64) *RedeemCodeUpdate {
	_u.mutation.AddWeeklyLimitUsdSnapshot(v)
	return _u
}

// ClearWeeklyLimitUsdSnapshot clears the value of the "weekly_limit_usd_snapshot" field.
func (_u *RedeemCodeUpdate) ClearWeeklyLimitUsdSnapshot() *RedeemCodeUpdate {
	_u.mutation.ClearWeeklyLimitUsdSnapshot()
	return _u
}

// SetMonthlyLimitUsdSnapshot sets the "monthly_limit_usd_snapshot" field.
func (_u *RedeemCodeUpdate) SetMonthlyLimitUsdSnapshot(v float64) *RedeemCodeUpdate {
	_u.mutation.ResetMonthlyLimitUsdSnapshot()
	_u.mutation.SetMonthlyLimitUsdSnapshot(v)
	return _u
}

// SetNillableMonthlyLimitUsdSnapshot sets the "monthly_limit_usd_snapshot" field if the given value is not nil.
func (_u *RedeemCodeUpdate) SetNillableMonthlyLimitUsdSnapshot(v *float64) *RedeemCodeUpdate {
	if v != nil {
		_u.SetMonthlyLimitUsdSnapshot(*v)
	}
	return _u
}

// AddMonthlyLimitUsdSnapshot adds value to the "monthly_limit_usd_snapshot" field.
func (_u *RedeemCodeUpdate) AddMonthlyLimitUsdSnapshot(v float64) *RedeemCodeUpdate {
	_u.mutation.AddMonthlyLimitUsdSnapshot(v)
	return _u
}

// ClearMonthlyLimitUsdSnapshot clears the value of the "monthly_limit_usd_snapshot" field.
func (_u *RedeemCodeUpdate) ClearMonthlyLimitUsdSnapshot() *RedeemCodeUpdate {
	_u.mutation.ClearMonthlyLimitUsdSnapshot()
	return _u
}

// SetRateMultiplierSnapshot sets the "rate_multiplier_snapshot" field.
func (_u *RedeemCodeUpdate) SetRateMultiplierSnapshot(v float64) *RedeemCodeUpdate {
	_u.mutation.ResetRateMultiplierSnapshot()
	_u.mutation.SetRateMultiplierSnapshot(v)
	return _u
}

// SetNillableRateMultiplierSnapshot sets the "rate_multiplier_snapshot" field if the given value is not nil.
func (_u *RedeemCodeUpdate) SetNillableRateMultiplierSnapshot(v *float64) *RedeemCodeUpdate {
	if v != nil {
		_u.SetRateMultiplierSnapshot(*v)
	}
	return _u
}

// AddRateMultiplierSnapshot adds value to the "rate_multiplier_snapshot" field.
func (_u *RedeemCodeUpdate) AddRateMultiplierSnapshot(v float64) *RedeemCodeUpdate {
	_u.mutation.AddRateMultiplierSnapshot(v)
	return _u
}

// SetValidityDays sets the "validity_days" field.
func (_u *RedeemCodeUpdate) SetValidityDays(v int) *RedeemCodeUpdate {
	_u.mutation.ResetValidityDays()
	_u.mutation.SetValidityDays(v)
	return _u
}

// SetNillableValidityDays sets the "validity_days" field if the given value is not nil.
func (_u *RedeemCodeUpdate) SetNillableValidityDays(v *int) *RedeemCodeUpdate {
	if v != nil {
		_u.SetValidityDays(*v)
	}
	return _u
}

// AddValidityDays adds value to the "validity_days" field.
func (_u *RedeemCodeUpdate) AddValidityDays(v int) *RedeemCodeUpdate {
	_u.mutation.AddValidityDays(v)
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *RedeemCodeUpdate) SetUserID(id int64) *RedeemCodeUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (_u *RedeemCodeUpdate) SetNillableUserID(id *int64) *RedeemCodeUpdate {
	if id != nil {
		_u = _u.SetUserID(*id)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *RedeemCodeUpdate) SetUser(v *User) *RedeemCodeUpdate {
	return _u.SetUserID(v.ID)
}

// SetSubscriptionPlan sets the "subscription_plan" edge to the SubscriptionPlan entity.
func (_u *RedeemCodeUpdate) SetSubscriptionPlan(v *SubscriptionPlan) *RedeemCodeUpdate {
	return _u.SetSubscriptionPlanID(v.ID)
}

// Mutation returns the RedeemCodeMutation object of the builder.
func (_u *RedeemCodeUpdate) Mutation() *RedeemCodeMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *RedeemCodeUpdate) ClearUser() *RedeemCodeUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearSubscriptionPlan clears the "subscription_plan" edge to the SubscriptionPlan entity.
func (_u *RedeemCodeUpdate) ClearSubscriptionPlan() *RedeemCodeUpdate {
	_u.mutation.ClearSubscriptionPlan()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RedeemCodeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RedeemCodeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RedeemCodeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RedeemCodeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RedeemCodeUpdate) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := redeemcode.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "RedeemCode.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := redeemcode.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "RedeemCode.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := redeemcode.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RedeemCode.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PlanNameSnapshot(); ok {
		if err := redeemcode.PlanNameSnapshotValidator(v); err != nil {
			return &ValidationError{Name: "plan_name_snapshot", err: fmt.Errorf(`ent: validator failed for field "RedeemCode.plan_name_snapshot": %w`, err)}
		}
	}
	return nil
}

func (_u *RedeemCodeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(redeemcode.Table, redeemcode.Columns, sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(redeemcode.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(redeemcode.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(redeemcode.FieldValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedValue(); ok {
		_spec.AddField(redeemcode.FieldValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(redeemcode.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UsedAt(); ok {
		_spec.SetField(redeemcode.FieldUsedAt, field.TypeTime, value)
	}
	if _u.mutation.UsedAtCleared() {
		_spec.ClearField(redeemcode.FieldUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(redeemcode.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(redeemcode.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(redeemcode.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(redeemcode.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PlanNameSnapshot(); ok {
		_spec.SetField(redeemcode.FieldPlanNameSnapshot, field.TypeString, value)
	}
	if value, ok := _u.mutation.DailyLimitUsdSnapshot(); ok {
		_spec.SetField(redeemcode.FieldDailyLimitUsdSnapshot, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDailyLimitUsdSnapshot(); ok {
		_spec.AddField(redeemcode.FieldDailyLimitUsdSnapshot, field.TypeFloat64, value)
	}
	if _u.mutation.DailyLimitUsdSnapshotCleared() {
		_spec.ClearField(redeemcode.FieldDailyLimitUsdSnapshot, field.TypeFloat64)
	}
	if value, ok := _u.mutation.WeeklyLimitUsdSnapshot(); ok {
		_spec.SetField(redeemcode.FieldWeeklyLimitUsdSnapshot, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedWeeklyLimitUsdSnapshot(); ok {
		_spec.AddField(redeemcode.FieldWeeklyLimitUsdSnapshot, field.TypeFloat64, value)
	}
	if _u.mutation.WeeklyLimitUsdSnapshotCleared() {
		_spec.ClearField(redeemcode.FieldWeeklyLimitUsdSnapshot, field.TypeFloat64)
	}
	if value, ok := _u.mutation.MonthlyLimitUsdSnapshot(); ok {
		_spec.SetField(redeemcode.FieldMonthlyLimitUsdSnapshot, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMonthlyLimitUsdSnapshot(); ok {
		_spec.AddField(redeemcode.FieldMonthlyLimitUsdSnapshot, field.TypeFloat64, value)
	}
	if _u.mutation.MonthlyLimitUsdSnapshotCleared() {
		_spec.ClearField(redeemcode.FieldMonthlyLimitUsdSnapshot, field.TypeFloat64)
	}
	if value, ok := _u.mutation.RateMultiplierSnapshot(); ok {
		_spec.SetField(redeemcode.FieldRateMultiplierSnapshot, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRateMultiplierSnapshot(); ok {
		_spec.AddField(redeemcode.FieldRateMultiplierSnapshot, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ValidityDays(); ok {
		_spec.SetField(redeemcode.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedValidityDays(); ok {
		_spec.AddField(redeemcode.FieldValidityDays, field.TypeInt, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   redeemcode.UserTable,
			Columns: []string{redeemcode.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   redeemcode.UserTable,
			Columns: []string{redeemcode.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SubscriptionPlanCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   redeemcode.SubscriptionPlanTable,
			Columns: []string{redeemcode.SubscriptionPlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionplan.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubscriptionPlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   redeemcode.SubscriptionPlanTable,
			Columns: []string{redeemcode.SubscriptionPlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionplan.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{redeemcode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RedeemCodeUpdateOne is the builder for updating a single RedeemCode entity.
type RedeemCodeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RedeemCodeMutation
}

// SetCode sets the "code" field.
func (_u *RedeemCodeUpdateOne) SetCode(v string) *RedeemCodeUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *RedeemCodeUpdateOne) SetNillableCode(v *string) *RedeemCodeUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *RedeemCodeUpdateOne) SetType(v string) *RedeemCodeUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *RedeemCodeUpdateOne) SetNillableType(v *string) *RedeemCodeUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *RedeemCodeUpdateOne) SetValue(v float64) *RedeemCodeUpdateOne {
	_u.mutation.ResetValue()
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *RedeemCodeUpdateOne) SetNillableValue(v *float64) *RedeemCodeUpdateOne {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// AddValue adds value to the "value" field.
func (_u *RedeemCodeUpdateOne) AddValue(v float64) *RedeemCodeUpdateOne {
	_u.mutation.AddValue(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *RedeemCodeUpdateOne) SetStatus(v string) *RedeemCodeUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RedeemCodeUpdateOne) SetNillableStatus(v *string) *RedeemCodeUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUsedBy sets the "used_by" field.
func (_u *RedeemCodeUpdateOne) SetUsedBy(v int64) *RedeemCodeUpdateOne {
	_u.mutation.SetUsedBy(v)
	return _u
}

// SetNillableUsedBy sets the "used_by" field if the given value is not nil.
func (_u *RedeemCodeUpdateOne) SetNillableUsedBy(v *int64) *RedeemCodeUpdateOne {
	if v != nil {
		_u.SetUsedBy(*v)
	}
	return _u
}

// ClearUsedBy clears the value of the "used_by" field.
func (_u *RedeemCodeUpdateOne) ClearUsedBy() *RedeemCodeUpdateOne {
	_u.mutation.ClearUsedBy()
	return _u
}

// SetUsedAt sets the "used_at" field.
func (_u *RedeemCodeUpdateOne) SetUsedAt(v time.Time) *RedeemCodeUpdateOne {
	_u.mutation.SetUsedAt(v)
	return _u
}

// SetNillableUsedAt sets the "used_at" field if the given value is not nil.
func (_u *RedeemCodeUpdateOne) SetNillableUsedAt(v *time.Time) *RedeemCodeUpdateOne {
	if v != nil {
		_u.SetUsedAt(*v)
	}
	return _u
}

// ClearUsedAt clears the value of the "used_at" field.
func (_u *RedeemCodeUpdateOne) ClearUsedAt() *RedeemCodeUpdateOne {
	_u.mutation.ClearUsedAt()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *RedeemCodeUpdateOne) SetNotes(v string) *RedeemCodeUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *RedeemCodeUpdateOne) SetNillableNotes(v *string) *RedeemCodeUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *RedeemCodeUpdateOne) ClearNotes() *RedeemCodeUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *RedeemCodeUpdateOne) SetExpiresAt(v time.Time) *RedeemCodeUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *RedeemCodeUpdateOne) SetNillableExpiresAt(v *time.Time) *RedeemCodeUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *RedeemCodeUpdateOne) ClearExpiresAt() *RedeemCodeUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetSubscriptionPlanID sets the "subscription_plan_id" field.
func (_u *RedeemCodeUpdateOne) SetSubscriptionPlanID(v int64) *RedeemCodeUpdateOne {
	_u.mutation.SetSubscriptionPlanID(v)
	return _u
}

// SetNillableSubscriptionPlanID sets the "subscription_plan_id" field if the given value is not nil.
func (_u *RedeemCodeUpdateOne) SetNillableSubscriptionPlanID(v *int64) *RedeemCodeUpdateOne {
	if v != nil {
		_u.SetSubscriptionPlanID(*v)
	}
	return _u
}

// ClearSubscriptionPlanID clears the value of the "subscription_plan_id" field.
func (_u *RedeemCodeUpdateOne) ClearSubscriptionPlanID() *RedeemCodeUpdateOne {
	_u.mutation.ClearSubscriptionPlanID()
	return _u
}

// SetPlanNameSnapshot sets the "plan_name_snapshot" field.
func (_u *RedeemCodeUpdateOne) SetPlanNameSnapshot(v string) *RedeemCodeUpdateOne {
	_u.mutation.SetPlanNameSnapshot(v)
	return _u
}

// SetNillablePlanNameSnapshot sets the "plan_name_snapshot" field if the given value is not nil.
func (_u *RedeemCodeUpdateOne) SetNillablePlanNameSnapshot(v *string) *RedeemCodeUpdateOne {
	if v != nil {
		_u.SetPlanNameSnapshot(*v)
	}
	return _u
}

// SetDailyLimitUsdSnapshot sets the "daily_limit_usd_snapshot" field.
func (_u *RedeemCodeUpdateOne) SetDailyLimitUsdSnapshot(v float64) *RedeemCodeUpdateOne {
	_u.mutation.ResetDailyLimitUsdSnapshot()
	_u.mutation.SetDailyLimitUsdSnapshot(v)
	return _u
}

// SetNillableDailyLimitUsdSnapshot sets the "daily_limit_usd_snapshot" field if the given value is not nil.
func (_u *RedeemCodeUpdateOne) SetNillableDailyLimitUsdSnapshot(v *float64) *RedeemCodeUpdateOne {
	if v != nil {
		_u.SetDailyLimitUsdSnapshot(*v)
	}
	return _u
}

// AddDailyLimitUsdSnapshot adds value to the "daily_limit_usd_snapshot" field.
func (_u *RedeemCodeUpdateOne) AddDailyLimitUsdSnapshot(v float64) *RedeemCodeUpdateOne {
	_u.mutation.AddDailyLimitUsdSnapshot(v)
	return _u
}

// ClearDailyLimitUsdSnapshot clears the value of the "daily_limit_usd_snapshot" field.
func (_u *RedeemCodeUpdateOne) ClearDailyLimitUsdSnapshot() *RedeemCodeUpdateOne {
	_u.mutation.ClearDailyLimitUsdSnapshot()
	return _u
}

// SetWeeklyLimitUsdSnapshot sets the "weekly_limit_usd_snapshot" field.
func (_u *RedeemCodeUpdateOne) SetWeeklyLimitUsdSnapshot(v float64) *RedeemCodeUpdateOne {
	_u.mutation.ResetWeeklyLimitUsdSnapshot()
	_u.mutation.SetWeeklyLimitUsdSnapshot(v)
	return _u
}

// SetNillableWeeklyLimitUsdSnapshot sets the "weekly_limit_usd_snapshot" field if the given value is not nil.
func (_u *RedeemCodeUpdateOne) SetNillableWeeklyLimitUsdSnapshot(v *float64) *RedeemCodeUpdateOne {
	if v != nil {
		_u.SetWeeklyLimitUsdSnapshot(*v)
	}
	return _u
}

// AddWeeklyLimitUsdSnapshot adds value to the "weekly_limit_usd_snapshot" field.
func (_u *RedeemCodeUpdateOne) AddWeeklyLimitUsdSnapshot(v float64) *RedeemCodeUpdateOne {
	_u.mutation.AddWeeklyLimitUsdSnapshot(v)
	return _u
}

// ClearWeeklyLimitUsdSnapshot clears the value of the "weekly_limit_usd_snapshot" field.
func (_u *RedeemCodeUpdateOne) ClearWeeklyLimitUsdSnapshot() *RedeemCodeUpdateOne {
	_u.mutation.ClearWeeklyLimitUsdSnapshot()
	return _u
}

// SetMonthlyLimitUsdSnapshot sets the "monthly_limit_usd_snapshot" field.
func (_u *RedeemCodeUpdateOne) SetMonthlyLimitUsdSnapshot(v float64) *RedeemCodeUpdateOne {
	_u.mutation.ResetMonthlyLimitUsdSnapshot()
	_u.mutation.SetMonthlyLimitUsdSnapshot(v)
	return _u
}

// SetNillableMonthlyLimitUsdSnapshot sets the "monthly_limit_usd_snapshot" field if the given value is not nil.
func (_u *RedeemCodeUpdateOne) SetNillableMonthlyLimitUsdSnapshot(v *float64) *RedeemCodeUpdateOne {
	if v != nil {
		_u.SetMonthlyLimitUsdSnapshot(*v)
	}
	return _u
}

// AddMonthlyLimitUsdSnapshot adds value to the "monthly_limit_usd_snapshot" field.
func (_u *RedeemCodeUpdateOne) AddMonthlyLimitUsdSnapshot(v float64) *RedeemCodeUpdateOne {
	_u.mutation.AddMonthlyLimitUsdSnapshot(v)
	return _u
}

// ClearMonthlyLimitUsdSnapshot clears the value of the "monthly_limit_usd_snapshot" field.
func (_u *RedeemCodeUpdateOne) ClearMonthlyLimitUsdSnapshot() *RedeemCodeUpdateOne {
	_u.mutation.ClearMonthlyLimitUsdSnapshot()
	return _u
}

// SetRateMultiplierSnapshot sets the "rate_multiplier_snapshot" field.
func (_u *RedeemCodeUpdateOne) SetRateMultiplierSnapshot(v float64) *RedeemCodeUpdateOne {
	_u.mutation.ResetRateMultiplierSnapshot()
	_u.mutation.SetRateMultiplierSnapshot(v)
	return _u
}

// SetNillableRateMultiplierSnapshot sets the "rate_multiplier_snapshot" field if the given value is not nil.
func (_u *RedeemCodeUpdateOne) SetNillableRateMultiplierSnapshot(v *float64) *RedeemCodeUpdateOne {
	if v != nil {
		_u.SetRateMultiplierSnapshot(*v)
	}
	return _u
}

// AddRateMultiplierSnapshot adds value to the "rate_multiplier_snapshot" field.
func (_u *RedeemCodeUpdateOne) AddRateMultiplierSnapshot(v float64) *RedeemCodeUpdateOne {
	_u.mutation.AddRateMultiplierSnapshot(v)
	return _u
}

// SetValidityDays sets the "validity_days" field.
func (_u *RedeemCodeUpdateOne) SetValidityDays(v int) *RedeemCodeUpdateOne {
	_u.mutation.ResetValidityDays()
	_u.mutation.SetValidityDays(v)
	return _u
}

// SetNillableValidityDays sets the "validity_days" field if the given value is not nil.
func (_u *RedeemCodeUpdateOne) SetNillableValidityDays(v *int) *RedeemCodeUpdateOne {
	if v != nil {
		_u.SetValidityDays(*v)
	}
	return _u
}

// AddValidityDays adds value to the "validity_days" field.
func (_u *RedeemCodeUpdateOne) AddValidityDays(v int) *RedeemCodeUpdateOne {
	_u.mutation.AddValidityDays(v)
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *RedeemCodeUpdateOne) SetUserID(id int64) *RedeemCodeUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (_u *RedeemCodeUpdateOne) SetNillableUserID(id *int64) *RedeemCodeUpdateOne {
	if id != nil {
		_u = _u.SetUserID(*id)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *RedeemCodeUpdateOne) SetUser(v *User) *RedeemCodeUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetSubscriptionPlan sets the "subscription_plan" edge to the SubscriptionPlan entity.
func (_u *RedeemCodeUpdateOne) SetSubscriptionPlan(v *SubscriptionPlan) *RedeemCodeUpdateOne {
	return _u.SetSubscriptionPlanID(v.ID)
}

// Mutation returns the RedeemCodeMutation object of the builder.
func (_u *RedeemCodeUpdateOne) Mutation() *RedeemCodeMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *RedeemCodeUpdateOne) ClearUser() *RedeemCodeUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearSubscriptionPlan clears the "subscription_plan" edge to the SubscriptionPlan entity.
func (_u *RedeemCodeUpdateOne) ClearSubscriptionPlan() *RedeemCodeUpdateOne {
	_u.mutation.ClearSubscriptionPlan()
	return _u
}

// Where appends a list predicates to the RedeemCodeUpdate builder.
func (_u *RedeemCodeUpdateOne) Where(ps ...predicate.RedeemCode) *RedeemCodeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RedeemCodeUpdateOne) Select(field string, fields ...string) *RedeemCodeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RedeemCode entity.
func (_u *RedeemCodeUpdateOne) Save(ctx context.Context) (*RedeemCode, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RedeemCodeUpdateOne) SaveX(ctx context.Context) *RedeemCode {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RedeemCodeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RedeemCodeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RedeemCodeUpdateOne) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := redeemcode.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "RedeemCode.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := redeemcode.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "RedeemCode.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := redeemcode.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RedeemCode.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PlanNameSnapshot(); ok {
		if err := redeemcode.PlanNameSnapshotValidator(v); err != nil {
			return &ValidationError{Name: "plan_name_snapshot", err: fmt.Errorf(`ent: validator failed for field "RedeemCode.plan_name_snapshot": %w`, err)}
		}
	}
	return nil
}

func (_u *RedeemCodeUpdateOne) sqlSave(ctx context.Context) (_node *RedeemCode, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(redeemcode.Table, redeemcode.Columns, sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RedeemCode.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, redeemcode.FieldID)
		for _, f := range fields {
			if !redeemcode.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != redeemcode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(redeemcode.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(redeemcode.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(redeemcode.FieldValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedValue(); ok {
		_spec.AddField(redeemcode.FieldValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(redeemcode.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UsedAt(); ok {
		_spec.SetField(redeemcode.FieldUsedAt, field.TypeTime, value)
	}
	if _u.mutation.UsedAtCleared() {
		_spec.ClearField(redeemcode.FieldUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(redeemcode.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(redeemcode.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(redeemcode.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(redeemcode.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PlanNameSnapshot(); ok {
		_spec.SetField(redeemcode.FieldPlanNameSnapshot, field.TypeString, value)
	}
	if value, ok := _u.mutation.DailyLimitUsdSnapshot(); ok {
		_spec.SetField(redeemcode.FieldDailyLimitUsdSnapshot, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDailyLimitUsdSnapshot(); ok {
		_spec.AddField(redeemcode.FieldDailyLimitUsdSnapshot, field.TypeFloat64, value)
	}
	if _u.mutation.DailyLimitUsdSnapshotCleared() {
		_spec.ClearField(redeemcode.FieldDailyLimitUsdSnapshot, field.TypeFloat64)
	}
	if value, ok := _u.mutation.WeeklyLimitUsdSnapshot(); ok {
		_spec.SetField(redeemcode.FieldWeeklyLimitUsdSnapshot, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedWeeklyLimitUsdSnapshot(); ok {
		_spec.AddField(redeemcode.FieldWeeklyLimitUsdSnapshot, field.TypeFloat64, value)
	}
	if _u.mutation.WeeklyLimitUsdSnapshotCleared() {
		_spec.ClearField(redeemcode.FieldWeeklyLimitUsdSnapshot, field.TypeFloat64)
	}
	if value, ok := _u.mutation.MonthlyLimitUsdSnapshot(); ok {
		_spec.SetField(redeemcode.FieldMonthlyLimitUsdSnapshot, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMonthlyLimitUsdSnapshot(); ok {
		_spec.AddField(redeemcode.FieldMonthlyLimitUsdSnapshot, field.TypeFloat64, value)
	}
	if _u.mutation.MonthlyLimitUsdSnapshotCleared() {
		_spec.ClearField(redeemcode.FieldMonthlyLimitUsdSnapshot, field.TypeFloat64)
	}
	if value, ok := _u.mutation.RateMultiplierSnapshot(); ok {
		_spec.SetField(redeemcode.FieldRateMultiplierSnapshot, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRateMultiplierSnapshot(); ok {
		_spec.AddField(redeemcode.FieldRateMultiplierSnapshot, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ValidityDays(); ok {
		_spec.SetField(redeemcode.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedValidityDays(); ok {
		_spec.AddField(redeemcode.FieldValidityDays, field.TypeInt, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   redeemcode.UserTable,
			Columns: []string{redeemcode.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   redeemcode.UserTable,
			Columns: []string{redeemcode.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SubscriptionPlanCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   redeemcode.SubscriptionPlanTable,
			Columns: []string{redeemcode.SubscriptionPlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionplan.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubscriptionPlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   redeemcode.SubscriptionPlanTable,
			Columns: []string{redeemcode.SubscriptionPlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionplan.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RedeemCode{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{redeemcode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
